saleor/saleor-docs

website/static/css/copy.css
website/static/css/layout.css

This PR implements bunch of tweaks that we've dissed previous week.

Frontend fixes

---

.circleci/config.yml

This PR allows deploying the docs only from the master branch.

Deploy the docs only from the master branch

---

docs/architecture/intro.md
docs/architecture/search.md
docs/deployment/heroku.md
docs/getting-started/configuration.md
docs/getting-started/installation-linux.md
docs/guides/email-integration.md

This PR adds missing architecture summary page and fixes internal links that were pointing to old read the docs page.

Fix broken links

---

docs/dashboard/configuration/products.md
docs/dashboard/using-saleor.md

Please review the _How to add a product type_ section - thanks!

product types updated with new way of adding variant attributes

---

docs/advanced/extensions.md
docs/dashboard/configuration/plugins.md
website/sidebars.json

Hey, have a look at both topics, please. The Extensions one is only modified with the Note added in the beginning and a link to Plugins topics.

plugins topic added & extensions topic modified

---

docs/api-process/check-out.md
docs/api-process/product.md

please, add your code snippets

Checkout process topic

---

docs/api-process/check-out.md
docs/api-process/product.md

This PR adds the "How to obtain a product" guide which describes getting a list of products, filtering, sorting, and getting a single product in our API.

Obtaining product

---

docs/advanced/running-tests.md
docs/api-process/product.md
docs/contributing/coding-style.md
docs/dashboard/catalog/categories.md
docs/dashboard/catalog/intro.md
docs/dashboard/systemwide/seo-smo.md
docs/getting-started/docker.md
docs/getting-started/installation-linux.md
docs/getting-started/installation-macos.md
docs/guides/email-integration.md
docs/integrations/googleforretail.md
docs/integrations/intro.md
docs/integrations/recaptcha.md
website/versioned_docs/version-2.8.0/contributing/coding-style.md
website/versioned_docs/version-2.8.0/customization/docker.md
website/versioned_docs/version-2.8.0/customization/running-tests.md
website/versioned_docs/version-2.8.0/dashboard/catalog/intro.md
website/versioned_docs/version-2.8.0/getting-started/installation-linux.md
website/versioned_docs/version-2.8.0/getting-started/installation-macos.md
website/versioned_docs/version-2.8.0/guides/email-integration.md
website/versioned_docs/version-2.8.0/guides/recaptcha.md
website/versioned_docs/version-2.8.0/integrations/googleforretail.md

This PR makes documentation even better! :smiley:

Improve docs

---

docs/advanced/managing-dependencies.md
docs/advanced/running-tests.md
docs/contributing/coding-style.md

Updated docs with how to use poetry instead of pipenv.

Update docs with poetry usage

---

README.md
docs/api-reference.md

Update API reference to include the latest changes from Saleor core.

Update API reference

---

website/siteConfig.js
website/static/css/code-block-copy-button.css
website/static/css/copy.css
website/static/js/code-block-copy-button.js

Add copy button on code block

---

docs/api-process/check-out.md
docs/api/authenticate.md
docs/api/error-handling.md
docs/api/example-query.md
docs/api/metadata.md
docs/api/pagination.md
website/versioned_docs/version-2.8.0/architecture/graphql.md

- Fix code highlighting bug (see [this screenshot](https://user-images.githubusercontent.com/4408379/66672921-2ac7c580-ec68-11e9-9685-ec50be06553d.png) :open_mouth: )
- Add `query` in GraphQL examples for consistency
- Little code style fix

Improve docs, part 2

---

docs/dashboard/catalog/products.md
docs/dashboard/using-saleor.md

Document two features of list views - sorting and search bars.

Update documentation of list views

---

website/static/css/footer.css

Fixes #76 @patrys @mirekm @derenio sir plz review

Fix signup button

---

docs/advanced/extensions.md
website/versioned_docs/version-2.9.0/advanced/extensions.md

The sample code was without `class` structure.

Fix code section in extensions

---

docs/getting-started/installation-linux.md
docs/getting-started/installation-macos.md
docs/getting-started/installation-windows.md

After removed build-assets from saleor it doesn't work anymore.

Remove build assets installation step

---

docs/customization/emails.md
docs/getting-started/installation-linux.md
docs/getting-started/installation-macos.md
docs/getting-started/installation-windows.md

As we discussed we should provide pre-compiled email templates instead of forcing user to compile them on start. Should be merged along with backend changes on https://github.com/mirumee/saleor/pull/5260.

Update email compile related docs

---

docs/getting-started/docker.md

Docker installation notes, changes according to
https://github.com/mirumee/saleor-platform/pull/1
https://github.com/mirumee/saleor/pull/5278

Modify docker installation notes for saleor platform

---

website/sidebars.json

missing link along opentracing

Add link to jaeger to sidebar menu

---

docs/advanced/extensions.md

It seems like ExtensionsManager is not in core anymore so I wanted to update the docs to correct this :)

ExtensionsManager was moved out of core

---

docs/developer/extending/apps.mdx
docs/developer/running-saleor/background-tasks.mdx
website/sidebars.json

This PR adds documentation for:
- background tasks
- apps (service accounts)
- webhooks
Fixes #47

Background tasks and webhooks

---

website/versioned_docs/version-2.9.0/getting-started/docker.md

I've been reading comments on Gitter and Spectrum seeing that docs are out of date. I would like to help contribute and update them if possible.
This is my first PR so unsure if i'm doing it correctly. Please let me know if i can help, thank you.

Update Docker Docs getting started

---

docs/developer/checkout.mdx

We changed the backend to use plugin ID instead of display names.

Update checkout docs about using payment ID

---

docs/developer/extending/plugins.mdx

Updated plugins page related to renaming extensions into plugins.

Update plugins page

---

docs/developer.mdx
docs/developer/community/faq.mdx
website/sidebars.json
website/versioned_docs/version-2.10/developer.mdx
website/versioned_docs/version-2.10/developer/community/faq.mdx
website/versioned_sidebars/version-2.10-sidebars.json

Content from Karol, reformatted, and updated to 2.10

Add FAQ to the community section

---

docs/developer/extending/plugins.mdx

This is the documentation change related to https://github.com/mirumee/saleor/pull/5686

Document plugin discovery

---

docs/developer/extending/apps.mdx
website/components/Chart/index.jsx
website/components/Chart/styles.css

Extend Apps docuentation

---

website/components/Chart/index.jsx
website/components/Chart/styles.css

Update chart styling - changes copied from #132, because I need it in `add-export-products-section`.

Update chart styling

---

docs/developer/extending/api/errors.mdx
website/sidebars.json

Add documentation about extending errors.

Add guide how to extend errors

---

docs/developer/extending/payment-gateways.mdx
website/versioned_docs/version-2.10/developer/extending/payment-gateways.mdx

Update developer payment-gateways section - some part of this section was out-of-date.

Update developer payment-gateways section

---

docs/developer/extending/api/sorters.mdx
website/sidebars.json
website/versioned_docs/version-2.10/developer/extending/api/sorters.mdx
website/versioned_sidebars/version-2.10-sidebars.json

Add document how to add sorter to query resolver and how to customize it.

Add sorters section

---

docs/developer/running-saleor/configuration.mdx
docs/developer/users.mdx

Update docs for changes from PR: https://github.com/mirumee/saleor/pull/5734

Update jwt section

---

docs/developer/checkout.mdx
docs/developer/extending/payment-gateways.mdx

Add information about supported currencies in gateways.

Add info about supported currencies in payment gateways

---

docs/developer/checkout.mdx

Few things were outdated and required corrections in the playground.

Update checkout mutation code in checkout section

---

docs/developer.mdx
docs/developer/export-products.mdx
website/sidebars.json

Add documentation about exporting products.

Add export products section

---

docs/developer/extending/apps.mdx

Update error type in app mutations

---

docs/api-reference.md
docs/developer/extending/apps.mdx

https://github.com/mirumee/saleor/pull/5837

Update weebhook events for checkout

---

docs/developer/extending/plugins.mdx

https://github.com/mirumee/saleor/pull/5884

Add section for webhook handler in plugin

---

docs/developer/running-saleor/configuration.mdx

I've seen community members editing the settings file directly

Document how to set environment variables in Docker containers

---

docs/api-reference.md

Update product API reference with new fields:
- availableForPurchase
- isAvailableForPurchase 
- visibleInListings

Update product API reference fields

---

docs/developer.mdx
website/versioned_docs/version-2.10/developer.mdx

Restores missing file extensions.

Fix links that were accidentally broken

---

docs/api-reference.md
docs/developer/extending/apps.mdx

Changes for https://github.com/mirumee/saleor/pull/6219

Update permission list with manage product types and attributes

---

docs/developer/checkout.mdx

The current docs are not up to date for the current structure of the Checkout type.

Update the checkout docs

---

docs/api-reference.md

Bump API reference to match with 2.11.0

Bump API reference

---

docs/developer/metadata.mdx

I want to add information in meta section about added meta to warehouse.

Add information about added meta to warehouse

---

docs/developer/slug-fields.mdx
website/sidebars.js

Added slug field description for our conventions category.

Add slug field description

---

website/package-lock.json
website/package.json

Seems i had old entries in my node_modules. Heres patch fixing it for the rest of team.

Add mising plugin entry in package json

---

website/package-lock.json
website/package.json

- 2.5gb ram seems to be minimal we need for build (if I get it right, we are safe below actions limit https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources )
- bumped versions to latest ones (tested build and dev server, both "work on my machine")

Fix build and bump versions

---

.github/workflows/test.yml
docs/developer.mdx
docs/developer/users.mdx
website/sidebars.js

Added test workflow to ensure, that PRs are building properly.
Also small fix for the wrong URL to the extending page.

Test builds on pr

---

.github/workflows/main.yml

Use same config as our storefront CI actions.

Use aws configure action

---

website/docusaurus.config.js
website/versioned_docs/version-2.9.0/developer.mdx

Navbar items are now linking to the chosen version instead of force redirect to last stable.

Make navbar itemv version aware

---

docs/developer/available-plugins/openid_connect.mdx
docs/developer/extending/plugins.mdx
website/sidebars.js

- Add plugins section
- Add a section for OpenIDConnect plugin

OpenID Connect dev chapter

---

README.md
docs/developer/running-saleor/background-tasks.mdx
website/versioned_docs/version-2.10/developer/running-saleor/background-tasks.mdx
website/versioned_docs/version-2.11/developer/running-saleor/background-tasks.mdx
website/versioned_docs/version-2.9.0/advanced/debug-tools.md
website/versioned_docs/version-2.9.0/advanced/internationalization.md
website/versioned_docs/version-2.9.0/advanced/running-tests.md
website/versioned_docs/version-2.9.0/contributing/coding-style.md
website/versioned_docs/version-2.9.0/customization/emails.md
website/versioned_docs/version-2.9.0/customization/thumbnails.md
website/versioned_docs/version-2.9.0/deployment/docker.md
website/versioned_docs/version-2.9.0/deployment/heroku.md
website/versioned_docs/version-2.9.0/getting-started/creating-superuser.md
website/versioned_docs/version-2.9.0/getting-started/docker.md
website/versioned_docs/version-2.9.0/getting-started/example-data.md
website/versioned_docs/version-2.9.0/getting-started/installation-linux.md
website/versioned_docs/version-2.9.0/getting-started/installation-macos.md
website/versioned_docs/version-2.9.0/integrations/elasticsearch.md
website/versioned_docs/version-2.9.0/integrations/googleforretail.md
website/versioned_docs/version-2.9.0/integrations/openexchangerates.md

Fix #125
The dollar sign inside code examples make copying harder than it needs to be.

Removed $ from commands for easier copy

---

docs/developer/available-plugins/dummy-credit-card.mdx
docs/developer/extending/plugins.mdx
docs/developer/running-saleor/dummy-payment.mdx
website/sidebars.js

Add dummy payment section with card numbers which can be used to checking different responses.

Add dummy payment section

---

docs/dashboard/orders.md

Related to https://github.com/mirumee/saleor/pull/6829

Docs on payments and allocations behavior on unconfirmed order

---

docs/developer/products.mdx

Based on developer feedback, I would like to clarify how quantities behave in API

Clarify stock quantities query

---

docs/developer/extending/apps/key-concepts.mdx

Related PR: https://github.com/mirumee/saleor/pull/7227

Update docs related to SQS fifo queues

---

website/versioned_docs/version-2.11/dashboard/configuration/plugins.md

Fix link in versioned docs

---

docs/developer/extending/apps/key-concepts.mdx
docs/developer/extending/apps/sample-webhook-payloads.mdx
docs/developer/extending/payment-gateways.mdx

Docs for https://github.com/mirumee/saleor/pull/7044.

Add docs for payment webhooks

---

README.md
website/package-lock.json
website/package.json

One of nested dependencies were causing issues with production build styles.

Fix prod build

---

website/docusaurus.config.js
website/package-lock.json
website/package.json

- a bit faster dev experience
- reduced build time from 7 to 5 minutes

Add esbuild and bump docusaurus

---

docs/developer/attributes.mdx

- Described input types
- Example query to fetch all attributes
- Example query to fetch attributes assigned to a product
Close #80

Improve attribute API docs

---

docs/developer/users.mdx

Channel argument description was missing.
Also added rationale behind this change.

Update channel argument in account registration

---

README.md
docs/style-guide.mdx

Having such a page will help us with testing stack updates and visual improvements.

Add style guide page

---

docs/developer/available-plugins/openid-connect.mdx

It adds a description for usage of the permissions field

Update oidc docs after adding support for accessToken.permission field

---

docs/developer/available-plugins/user-emails.mdx

As in title.
Related PR:
https://github.com/mirumee/saleor/pull/7764

Update email developer docs section for gift cards

---

docs/developer/address.mdx
docs/developer/checkout.mdx
website/sidebars.js

- explain lack of cart
- document cartlines operations
- cover different payments flow
- add address validation page
Fix #79

Enhance checkout docs

---

docs/developer/extending/apps/sample-webhook-payloads.mdx

Update Webhook payload section with `order.number`.

Update Webhook payload section

---

docs/developer/metadata.mdx

Updates for https://github.com/saleor/saleor/pull/8426

Update docs for metadata - add note that token can be used for modyfing checkout and order metadata

---

docs/developer/running-saleor/configuration.mdx

Add documentation for `GRAPHQL_QUERY_MAX_COMPLEXITY` env setting introduced in https://github.com/saleor/saleor/pull/8526

Add doc for GRAPHQL_QUERY_MAX_COMPLEXITY

---

docs/developer/checkout.mdx

Update docs for changes for anonymous checkouts.
Should be merged with https://github.com/saleor/saleor/pull/8533.

Update docs for anonymous checkouts

---

README.md
docs/developer.mdx
docs/developer/api-reference.mdx
docs/developer/api-reference/enums/gift-card-error-code.mdx
docs/developer/api-reference/inputs/export-gift-cards-input.mdx
docs/developer/api-reference/inputs/export-products-input.mdx
docs/developer/api-reference/inputs/gift-card-bulk-create-input.mdx
docs/developer/api-reference/inputs/gift-card-event-filter-input.mdx
docs/developer/api-reference/inputs/gift-card-filter-input.mdx
docs/developer/api-reference/inputs/order-filter-input.mdx
docs/developer/api-reference/mutations/export-gift-cards.mdx
docs/developer/api-reference/mutations/export-products.mdx
docs/developer/api-reference/mutations/gift-card-bulk-create.mdx
docs/developer/api-reference/objects/export-gift-cards.mdx
docs/developer/api-reference/objects/gift-card-bulk-create.mdx
docs/developer/api-reference/objects/gift-card.mdx
docs/developer/export/export-gift-cards.mdx
docs/developer/export/export-overview.mdx
docs/developer/export/export-products.mdx
docs/developer/gift-cards.mdx
docs/developer/products.mdx
sidebars.js

- Update api reference
- Add gift cards section
- Refactor export products section
- Add export overview
- Add export gift cards section
- 
⚠️
Should be merged with mirumee/saleor#7977.

Gift cards

---

docs/developer/extending/apps/extensions.mdx
docs/developer/extending/apps/manifest.mdx
sidebars.js

It adds more context to how App's extensions can be used.

Add basic explanaition of app's extensions

---

docs/dashboard/configuration/plugins/adyen.md
docs/developer/available-plugins/adyen.mdx
sidebars.js

- Add missing dev chapter for Adyen plugin. 
- Update configuration of Adyen plugin to match with the current available functionalities

Adyen plugin - dev chapter + update of configuration part

---

docs/developer/api-conventions/error-handling.mdx

Use updated error format and expand enums info.

Update error handling page

---

docs/developer/upgrade-guide/2-11-to-3-0.mdx
sidebars.js

Add upgrade guide for the Saleor 3.0.

Version upgrade guide

---

docs/developer/permissions.mdx
docs/developer/running-saleor/configuration.mdx
docs/developer/users.mdx

We changed the way of signing JWT tokens (HS256 -> RS256).  The changes for this update: https://github.com/saleor/saleor/pull/7990

Add note about new way of signing and verifing a JWT tokens

---

docs/dashboard/configuration/warehouses.mdx
docs/developer/gift-cards.mdx

Added warnings to gift cards and click & collect docs.
Reduced the gift card examples to make them easier to understand.

Add Feature Preview warnings

---

docs/developer/checkout.mdx
docs/developer/extending/apps/synchronous-webhooks.mdx

This PR documents 2 new features in Saleor:
- https://github.com/saleor/saleor/pull/8399
- https://github.com/saleor/saleor/pull/7975
@krzysztofwolski @korycins

Document sync webhooks for shipping

---

docs/developer/extending/apps/synchronous-webhooks.mdx

Add Feature Preview warning to shipping webhooks

---

docs/developer/running-saleor/read-replicas.mdx
sidebars.js

Documentation for the read replicas

Documentation for the read replicas

---

README.md
docs/dashboard/apps.md
docusaurus.config.js
src/pages/index.js

Also configured a redirect from the old URLs to the new ones.

Change the version used in URLs from 3.0 to 3.x

---

docs/developer/users.mdx

Fix anchors

---

docs/developer/metadata.mdx

Also, link them to the appropriate object types.

Update the list of objects implementing metadata

---

docs/developer/extending/apps/synchronous-webhooks.mdx

Fixed by this PR: https://github.com/saleor/saleor/pull/9333

Fix incorrect value for channel field 

---

docs/developer/available-plugins/admin-emails.mdx

Related to https://github.com/mirumee/saleor/pull/7993.
⚠️ 
Should be merged with https://github.com/mirumee/saleor/pull/7977.

Update admin emails events for export

---

docs/developer/available-plugins/user-emails.mdx
docs/developer/extending/apps/sample-webhook-payloads.mdx
docs/developer/upgrade-guide/3-1-to-3-2.mdx
sidebars.js

Related to [Saleor #9388](https://github.com/saleor/saleor/pull/9388)

Update email palyoads

---

docs/developer/api-reference/enums/permission-enum.mdx
docs/developer/api-reference/inputs/checkout-line-input.mdx
docs/developer/api-reference/inputs/checkout-line-update-input.mdx
docs/developer/api-reference/mutations/checkout-lines-update.mdx
docs/developer/checkout.mdx
docs/developer/permissions.mdx

Updates for custom prices feature.
Related to [#9393](https://github.com/saleor/saleor/pull/9393).

Custom prices

---

README.md
docs/developer/available-plugins/adyen.mdx
docs/developer/available-plugins/openid-connect.mdx
docs/developer/community/faq.mdx
docs/developer/community/support.mdx
docs/developer/extending/apps/installing-apps.mdx
docs/developer/extending/apps/manifest.mdx
docs/developer/getting-started/architecture.mdx
docs/developer/installation.mdx
docs/developer/installation/windows.mdx
docs/developer/users.mdx

Updated references of the storefront to the SRS

Migrate storefront to the SRS

---

docs/developer/community/contributing.mdx

Extend contribution guide with info about:
- File structure
- Testing
- Tips and recommendations
- Pull requests
- Changelog
Drop expired `Translations` part.

Improve contribution guide

---

docs/developer/api-reference/enums/webhook-event-type-async-enum.mdx
docs/developer/api-reference/enums/webhook-event-type-enum.mdx
docs/developer/api-reference/enums/webhook-sample-event-type-enum.mdx
docs/developer/extending/apps/asynchronous-webhooks.mdx

PR with a change [here.](https://github.com/saleor/saleor/pull/9657)

New voucher related webhooks events added to enums.

---

docs/developer/community/contributing.mdx

Update `API description` part in contribution guide. Related to https://github.com/saleor/saleor/pull/9631

Update description part in contribution guide

---

docs/developer/api-reference/enums/webhook-event-type-async-enum.mdx
docs/developer/api-reference/enums/webhook-event-type-enum.mdx
docs/developer/extending/apps/asynchronous-webhooks.mdx

PR with a change [here.](https://github.com/saleor/saleor/pull/9746)

New warehouse related webhooks events added to enums.

---

docs/developer/extending/apps/extending-dashboard-with-apps.mdx

This documents changes from https://github.com/saleor/saleor/pull/9694

Add support for ORDER_* mountpoints for Apps

---

docs/developer/available-plugins/openid-connect.mdx

A minor improvement to the docs that makes it easier to verify scopes have been set up correctly with an external identity provider.

Sort permission scopes list alphabetically

---

docs/dashboard/configuration/warehouses.mdx

This limitation no longer exists

Remove inaccurate note

---

docs/developer/available-plugins/openid-connect.mdx

Input parameters should be provided as a variable otherwise mutations would yield input errors

Update OpenID broken examples

---

docs/cli.mdx
docs/developer.mdx
docs/developer/extending.mdx
docs/index.mdx
sidebars.js

This PR adds an initial version of the docs for Saleor CLI.

Add initial CLI docs

---

docs/developer.mdx
docs/developer/thumbnails.mdx
docs/developer/upgrade-guide/3-5-to-3-6.mdx
sidebars.js

Add docs for better media thumbnails

---

docs/developer/stock-allocation.mdx

Add short `click-and-collect` part to the `stock allocation` section.

Extend stock allocation section with a click and collect part

---

docs/developer/extending/apps/synchronous-webhooks/payment-webhooks.mdx

all credits go to @JannikZed from https://github.com/saleor/saleor-docs/pull/467

feat: :memo: update payment-webhooks with "kind" field

---

docs/developer/api-conventions/error-handling.mdx

Language improvements and style polishing.

Proofreading🔍: Error Handling

---

docs/developer/api-conventions/pagination.mdx

Language improvements, and minor style polishing.

Proofreading🔍: Pagination

---

docs/developer/api-conventions/prices.mdx

Language improvements and some grammar fixes.

Proofreading🔍: Prices

---

docs/developer/api-conventions/slug-fields.mdx

Proofreading🔍: Slug-fields

---

docs/developer/channels.mdx

Grammar fixes, word choice, and style polish.

Proofreading🔍: Channels

---

docs/developer/products.mdx

Fixed some word-choice issues and minor grammar mistakes. Also, clarified some lengthy sentences.

Proofreading🔍: Products

---

docs/developer/attributes.mdx

Minor improvements in terms of word choice and style. Grammar fixes.

Proofreading🔍: Attributes

---

docs/developer/checkout.mdx

Wording, sentence structure, and grammar improvements.

Proofreading🔍: Checkout

---

docs/developer/stock-allocation.mdx

Mostly sentence clarification with a bit of word choice.

Proofreading🔍: Stock Allocation

---

docs/developer/gift-cards.mdx

Fixed a few grammar mistakes and rewrote some sentences for better clarity.

Proofreading🔍: Gift Cards

---

docusaurus.config.js
package-lock.json
package.json
src/theme/Layout/index.js

**Note:**
I had to swizzle the `Layout` component because AFAIK, there was no "general wrapper" for the entire app.

Add Sentry integration

---

docs/developer/address.mdx

Mostly grammar fixes with a bit of sentence structure improvements.

Proofreading🔍: Address Validation

---

docs/developer/users.mdx

Mostly grammar and punctuation fixes, a bit of sentence clarification.

Proofreading🔍: Users

---

docs/developer/permissions.mdx

Word choice, punctuation fixes, and a bit of grammar polishing.

Proofreading🔍: Permissions

---

docs/developer/metadata.mdx

Proofreading🔍: Metadata

---

docs/developer/thumbnails.mdx

This article was reviewed previously, so just a small spot to clean up.

Proofreading🔍: Thumbnails

---

docs/developer/api-conventions/translations.mdx

Mostly grammar and punctuation fixes.

Proofreading🔍: Translations

---

docs/developer/export/export-gift-cards.mdx
docs/developer/export/export-overview.mdx
docs/developer/export/export-products.mdx

Language improvements in the Exporting Data section.

Proofreading🔍: Exporting Data

---

docs/developer/extending.mdx

Fixed grammar and rephrased some wordy phrases.

Proofreading🔍: Extending Saleor

---

docs/developer/extending/apps/installing-apps.mdx

Correcting grammar mistakes and working on language improvements.

Proofreading🔍: Installing Apps

---

docs/developer/extending/apps/asynchronous-webhooks.mdx

Mostly grammar fixes, a bit of rephrasing.

Proofreading🔍: Async Webhooks

---

docs/developer/extending/apps/synchronous-webhooks/key-concepts.mdx

Proofreading🔍: Sync Webhooks

---

docs/developer/extending/apps/synchronous-webhooks/shipping-webhooks.mdx

Proofreading🔍: Shipping Webhooks

---

docs/developer/extending/apps/synchronous-webhooks/tax-webhooks.mdx

Small improvements to language and grammar fixes.

Proofreading🔍: Tax webhooks

---

docs/developer/extending/apps/subscription-webhook-payloads.mdx

Grammar fixes, choice of words improvements, and rephrasing.

Proofreading🔍: Subscription Webhook Payloads

---

docs/developer/extending/apps/extending-dashboard-with-apps.mdx

Grammar fixes (mostly incorrect articles).

Proofreading🔍: Extending Dashboard

---

docs/developer/extending/apps/sample-webhook-payloads.mdx

Large code snippets mostly but I had to rephrase a few sentences.

Proofreading🔍: Webhook payloads

---

docs/developer/extending/apps/synchronous-webhooks/payment-webhooks.mdx

Proofreading🔍: Payment Webhooks

---

docs/developer/extending/apollo-federation.mdx

Grammar fixes and sentence restructuring.

Proofreading🔍: Apollo Federation

---

docs/developer/installation.mdx
docs/developer/installation/windows.mdx

Improved word choice and fixed some grammar.

Proofreading🔍: Installation

---

docs/developer/running-saleor/configuration.mdx

Fixed grammar mistakes and worked on improving sentence structure and word choice.

Proofreading🔍: Configuration

---

docs/developer/running-saleor/heroku.mdx

Mostly grammar fixes and a bit of word choice.

Proofreading🔍: Heroku

---

docs/developer/running-saleor/s3.mdx

Text layout improvements, and minor grammar fixes.

Proofreading🔍: Amazon S3

---

docs/developer/running-saleor/gcs.mdx

Proofreading🔍: GCS

---

docs/developer/running-saleor/docker.mdx

Proofreading🔍: Docker

---

docs/developer/running-saleor/debugging-emails.mdx

Proofreading🔍: Debugging Emails

---

docs/developer/running-saleor/exposing-instance.mdx

Proofreading🔍: Exposing Instance

---

docs/developer/running-saleor/monitoring.mdx

Proofreading🔍: Monitoring

---

docs/developer/running-saleor/background-tasks.mdx

Updated some phrases and sentence structure.

Proofreading🔍: Background Tasks

---

docs/developer/running-saleor/read-replicas.mdx

Proofreading🔍: Read Replicas

---

docs/developer/upgrade-guide/2-11-to-3-0.mdx
docs/developer/upgrade-guide/3-0-to-3-1.mdx

Fixed grammar and word choice.

Proofreading🔍: Upgrade Guide

---

docs/developer/community/faq.mdx

Mostly grammar fixes, with a bit of word choice improvements.

Proofreading🔍: FAQ

---

docs/developer/community/contributing.mdx

Fixed grammar and punctuation, and rephrased some sentences for clarity.

Proofreading🔍: Contributing

---

docs/developer/products.mdx

Extend the `Stock quantities` section with the explanation of how the `quantityAvailable` is calculated.

Extend product quantities section

---

docs/dashboard/before-you-start.md

Fixed grammar and clarified some sentences.

Proofreading🔍: Dashboard - Before You Start

---

docs/dashboard/home.md

Fixed grammar and punctuation mostly.

Proofreading🔍: Dashboard-Home

---

docs/dashboard/channels.md

Fixed grammar and rephrased some bits of text.

Proofreading🔍: Dashboard-Channels

---

docs/dashboard/catalog/products.md

Fixed grammar, and punctuation. Rephrased for clarity.

Proofreading🔍: Dashboard-Products

---

docs/dashboard/using-saleor.md

Fixing grammar and rephrasing.

Proofreading🔍: Dashboard-Using Saleor

---

docs/developer/api-reference/objects/calculate-taxes.mdx
docs/developer/api-reference/objects/taxable-object-discount.mdx
docs/developer/api-reference/objects/taxable-object-line.mdx
docs/developer/api-reference/objects/taxable-object.mdx
docs/developer/api-reference/unions/tax-source-line.mdx
docs/developer/api-reference/unions/tax-source-object.mdx
docs/developer/extending/apps/synchronous-webhooks/tax-webhooks.mdx

Update docs, for PR: https://github.com/saleor/saleor/pull/10433

Update docs about subscription for tax webhooks

---

docs/developer/thumbnails.mdx

Extend the thumbnails section with version specifications and caution regarding the issue with WebP

Extend thumbnails section with version specifications and caution 

---

docs/developer/extending/apps/apps-patterns/handling-external-webhooks.mdx
sidebars.js

Add external webhooks docs

---

docs/developer/extending/apps/developing-apps/apps-patterns/persistence-with-metadata-manager.mdx

Add metadata pattern docs

---

docs/developer/running-saleor/background-tasks.mdx

https://github.com/saleor/saleor/issues/11045

docs: :memo: upgrade documentation about discounted price

---

docs/developer/extending/apps/architecture/communication-between-app-and-saleor.mdx
sidebars.js

App communication docs

---

docusaurus.config.js
package.json

After the last version upgrade, we have OOM errors again.

Allocate more memory for the builds

---

docs/developer/community/contributing.mdx

Update contribution guide:
- add `Optimization` section
- add `Handling migrations between versions` section

Update contribution guide with optimization and migration handling

---

docs/developer/metadata.mdx
package-lock.json
package.json

Those were introduced in Saleor 3.3 but were never documented.

Add docs for metafield and metafields

---

docs/developer/available-plugins/adyen.mdx
docs/developer/checkout.mdx

- Extend the `checkout` page with refund info
- Extend `Adyen` page with refund info

Add info about possible payment refund

---

docs/developer/attributes.mdx
docs/developer/checkout.mdx
docs/developer/getting-started/deployment.mdx
docs/developer/installation.mdx
docs/developer/running-saleor/docker.mdx
docs/developer/setup.mdx
sidebars.js

I want to merge this change as it's rearrangement and adjustment od the _Deployment_ sub-page of Saleor Documentation.

WIP Adjustment of Deployment subpage

---

docs/developer/available-plugins/stripe.mdx

https://github.com/saleor/saleor/issues/8837

Fix Stripe payment intent parameter name

---

docs/developer/extending/apps/key-concepts.mdx

I want to merge this as it replaces the webhook card with the app quickstart.

Replace webhook card with quickstart

---

docs/setup/docker-compose.mdx

`collectstatic` is not needed, GitHub repository contains additional troubleshooting info.

Improve installation instructions

---

docs/setup/docker-compose.mdx

rel https://github.com/saleor/saleor-platform/pull/221

Link to specific saleor-platform troubleshooting section

---

docs/api-usage/authentication.mdx

This links directly to the Cognito API docs for OIDC.

Add Amazon Cognito to OIDC docs

---

docs/api-usage/authentication.mdx

Fixes https://github.com/saleor/react-storefront/issues/716

docs: 🔐 update authentication guide

---

docs/setup/docker-compose.mdx
docs/setup/docker-images.mdx
docs/setup/upgrading.mdx
package-lock.json
package.json

Update docs for `docker compose`, add docs for Dashboard container

---

docs/upgrade-guides/2-11-to-3-0.mdx
docs/upgrade-guides/3-0-to-3-1.mdx
docs/upgrade-guides/3-1-to-3-2.mdx
docs/upgrade-guides/3-11-to-3-12.mdx
docs/upgrade-guides/3-5-to-3-6.mdx

Migration upgrade guide. To be merged after succesfull resolving all PR's from issue: https://github.com/saleor/saleor/issues/11337

Add upgrade guide 3.11 to 3.12

---

.vscode/settings.json
docs/developer/filtering.mdx
sidebars.js

Add a filtering page describing what was introduced in [this PR](https://github.com/saleor/saleor/pull/11737).

Add filtering page

---

docs/api-usage/authentication.mdx

Fixes https://github.com/saleor/react-storefront/issues/663

Add link to example auth implementation

---

docs/index.mdx
package-lock.json
package.json
src/theme/DocItem/Paginator/index.js

This PR introduces [`giscus`](https://giscus.app/) to docs pages.
It's mounted to the `Pagniator` component.
By using `disableComments` in frontmatter you can turn off discussions for a specific page.

Add giscus

---

components/Feedback/index.js
components/Feedback/styles.module.css
docusaurus.config.js
package-lock.json
package.json
src/theme/DocItem/Footer/index.js

This PR adds a simple feedback survey in the `DocItem` `Footer` component

Feedback survey

---

docs/developer/thumbnails.mdx

Added missing formats and corrected the described behavior.

Update thumbnail docs

---

docusaurus.config.js
src/css/theme.css

Makes Mermaid charts monochromatic

Override the default Mermaid style

---

docs/developer/available-plugins/oidc.mdx
docs/developer/channels.mdx
docs/developer/extending/plugins.mdx
docs/developer/permissions.mdx
docs/upgrade-guides/3-12-to-3-13.mdx
docs/upgrade-guides/3.13-to-3.14.mdx

The docs for channel permission feature https://github.com/saleor/saleor/pull/10423

Channel permissions

---

docs/developer/app-store/apps/overview.mdx
docs/developer/app-store/overview.mdx
docs/developer/available-plugins/user-emails.mdx
docs/developer/community/faq.mdx
docs/developer/extending/payment-gateways.mdx
docs/developer/extending/plugins/overview.mdx
sidebars.js

Provide consistent navigation experience

Remove nesting

---

docs/developer/app-store/apps/crm.mdx
docs/developer/app-store/apps/taxes.mdx

This PR: https://github.com/saleor/apps/pull/439 changes logger implementation and renames variable that controls logger behavior
The PR updates env name

Update CRM and Taxes apps docs to display proper env variable for logging

---

docs/developer/extending/apps/developing-apps/troubleshooting.mdx
sidebars/apps-sidebar.js

The goal is to maintain such page and extend it every time community needs help - new topic/question can be written down for the future

Add troubleshooting page for apps development

---

docs/developer/app-store/apps/adyen.mdx

Rel: https://github.com/saleor/saleor-app-payment-adyen/pull/331

New endpoints in Adyen App

---

src/css/components/api-reference.css

|Before|After|
|------|------|
|<img width="1502" alt="image" src="https://github.com/saleor/saleor-docs/assets/779644/c2ca3712-549c-47ca-9ee1-aa665cfbaf34">|<img width="1502" alt="image" src="https://github.com/saleor/saleor-docs/assets/779644/bd7fbccf-e398-4030-a81e-67b6d3fb225d">|

Fix h1 for api-reference main page

---

docs/developer/thumbnails.mdx

The documentation was lacking information on how the proxy URL is created.
Connected to https://github.com/saleor/saleor/discussions/11117#

Add note about proxy url creation

---

docs/setup/docker-compose.mdx

Remove outdated note for `docker-compose` setup

---

docs/developer/filtering.mdx

Update filtering page with explenation how filtering by flat fields works

Improve filtering page

---

docs/api-reference/miscellaneous/scalars/metadata.mdx
docs/api-reference/taxes/mutations/tax-country-configuration-update.mdx
docs/api-storefront/miscellaneous/scalars/metadata.mdx

replace curly braces in unicode with glyph char

---

components/AppMetadata/AppMetadata.module.css
components/AppMetadata/AppMetadata.tsx
docs/developer/app-store/apps/cms.mdx
docs/developer/app-store/apps/crm.mdx
docs/developer/app-store/apps/emails-and-messages/overview.mdx
docs/developer/app-store/apps/invoices.mdx
docs/developer/app-store/apps/taxes/overview.mdx
src/css/primitives/colors.css
static/assets/icons/external-link.svg

App metadata component - improve UI and apply to docs

---

docs/developer/app-store/apps/taxes/architecture.mdx
docs/developer/app-store/apps/taxes/avatax/document-code.mdx
docs/developer/app-store/apps/taxes/avatax/document-recording.mdx
docs/developer/app-store/apps/taxes/avatax/entity-type.mdx
docs/developer/app-store/apps/taxes/avatax/tax-calculation-date.mdx
docs/developer/app-store/apps/taxes/overview.mdx
sidebars.js

related to: https://github.com/saleor/apps/pull/826/files

docs: :memo: add taxes/architecture and articles for mapping features

---

docs/developer/app-store/apps/adyen.mdx

Fixes https://github.com/saleor/saleor-app-payment-adyen/issues/357

Adyen App: Add details about payload

---

docs/developer/bulks/bulk-attributes.mdx
docs/developer/bulks/bulk-orders.mdx
docs/developer/bulks/error-policy.mdx
package-lock.json
sidebars.js

This adds `bulk-attributes` and `error-policy` sections.

Add docs for bulk attributes

---

docs/developer/community/contributing.mdx
docs/developer/community/zero-downtime-migrations.mdx
docs/setup/upgrading.mdx
sidebars.js

Documentation of zero-downtime migrations

Add zero-downtime documentation

---

docs/developer/extending/webhooks/synchronous-events/transaction.mdx
docs/developer/payments.mdx

Docs for the changes introduced in the RFC: https://github.com/saleor/saleor/issues/13605

Add customerIpAddress to transactionAPI

---

docs/setup/configuration.mdx

I want to add this change as it brings the "Updating domain configuration" and "ENABLE_SSL" paragraphs to "Server Configuration"

Add "updating domain configuration"

---

docs/developer/app-store/apps/segment.mdx

rel 
https://github.com/saleor/apps/pull/914/files

Update Segment app docs with new event mapping

---

versioned_docs/version-3.x/developer/app-store/apps/TEMPLATE.mdx
versioned_docs/version-3.x/developer/app-store/apps/invoices.mdx
versioned_docs/version-3.x/developer/app-store/apps/overview.mdx
versioned_docs/version-3.x/developer/app-store/apps/segment.mdx
versioned_docs/version-3.x/developer/app-store/apps/taxes/tax-codes.mdx
versioned_docs/version-3.x/developer/community/contributing.mdx
versioned_docs/version-3.x/developer/community/zero-downtime-migrations.mdx
versioned_docs/version-3.x/developer/extending/webhooks/synchronous-events/transaction.mdx
versioned_docs/version-3.x/developer/payments.mdx
versioned_docs/version-3.x/setup/configuration.mdx
versioned_docs/version-3.x/setup/docker-compose.mdx
versioned_docs/version-3.x/setup/upgrading.mdx
versioned_sidebars/version-3.x-sidebars.json

This PR brings `3.x` version up to date with `Canary`

Release 3.x

---

docs/developer/app-store/apps/crm.mdx
versioned_docs/version-3.x/developer/app-store/apps/crm.mdx

Segment app was released as a standalone one

Remove Segment app from CRM docs

---

docs/developer/checkout/problems.mdx
sidebars.js

As described in RFC: https://github.com/saleor/saleor/issues/12943

Provide a chapter to explain `Checkout.problems` and `CheckoutLine.problems` fields

---

docs/developer/extending/apps/architecture/server-and-client-side-calls.mdx
sidebars/apps-sidebar.js

This doc quickly explains difference between user token/auth token and appToken and gives some examples when to use which one

New Apps doc: API calls server side vs client side

---

.vscode/settings.json
docs/developer/checkout/finalizing.mdx
docs/developer/checkout/lines.mdx
docs/developer/checkout/overview.mdx
docs/developer/extending/webhooks/synchronous-events/transaction.mdx
docs/developer/payments.mdx
docusaurus.config.js
src/css/components/code.css
src/css/primitives/typography.css
versioned_docs/version-3.x/developer/extending/webhooks/synchronous-events/transaction.mdx
versioned_docs/version-3.x/developer/payments.mdx

Update guides to prioritize Payment Apps.
Fixes https://github.com/saleor/saleor-docs/issues/890
Related https://github.com/saleor/saleor-docs/issues/806

Update payments guide

---

docs/developer/app-store/apps/overview.mdx
docs/developer/extending/apps/developing-apps/app-sdk/app-bridge.md
docs/developer/extending/apps/developing-apps/app-template.mdx
docs/developer/extending/apps/developing-with-tunnels.mdx
docs/developer/extending/apps/quickstart.mdx
docs/developer/extending/apps/quickstart/creating-app.mdx
docs/developer/extending/webhooks/creating.mdx
versioned_docs/version-3.x/developer/app-store/apps/overview.mdx
versioned_docs/version-3.x/developer/extending/apps/developing-apps/app-sdk/app-bridge.md
versioned_docs/version-3.x/developer/extending/apps/developing-apps/app-template.mdx
versioned_docs/version-3.x/developer/extending/apps/developing-with-tunnels.mdx
versioned_docs/version-3.x/developer/extending/apps/quickstart.mdx
versioned_docs/version-3.x/developer/extending/apps/quickstart/creating-app.mdx
versioned_docs/version-3.x/developer/extending/webhooks/creating.mdx

Rename CLI app create to app template - #918
Update Tunneling Apps page - #915 
Fix AppBridge page typo - #909

Improvements

---

docs/developer/community/zero-downtime-migrations.mdx
versioned_docs/version-3.x/developer/community/zero-downtime-migrations.mdx

Update zero-downtime-migrations regarding to Additional Autodiscovery with Specified Related Names

zero-downtime-migrations page update

---

docs/api-reference/payments/enums/stored-payment-method-request-delete-result.mdx
docs/developer/extending/webhooks/synchronous-events/stored-payment-method.mdx
docs/developer/payments.mdx

RFC: https://github.com/saleor/saleor/issues/13395

[Programmatic payments] stored payment methods request delete

---

docs/developer/app-store/apps/overview.mdx
docs/developer/app-store/apps/search.mdx
sidebars.js

Docs for the [Search App](https://github.com/saleor/apps/tree/main/apps/search).
After the PR will be accepted, I'll copy the changes to the current docs version.

Add Search App documentation

---

docs/developer/extending/apps/developing-with-tunnels.mdx
versioned_docs/version-3.x/developer/extending/apps/developing-with-tunnels.mdx

Add VS Code tunnel as example of tunnel to use on apps devleopment

Add VSC tunnels docs

---

docs/developer/extending/apps/developing-apps/app-sdk/apl.md

Based on our discussion with developers and their use cases, decided to extend the Redis APL example with suggestions on how to use a single Redis instance for multiple environments.

Extend Redis APL example with suggestion on multi app usage

---

versioned_docs/version-3.x/developer/app-store/apps/overview.mdx
versioned_docs/version-3.x/developer/app-store/apps/search.mdx
versioned_sidebars/version-3.x-sidebars.json

Content has been reviewed in #934

Copy Search App doc to 3.x from dev

---

.github/workflows/test.yml

Cache Docusaurus for faster application rebuilds.
#899

Add build cache for test workflow

---

docs/developer/channels.mdx
docs/developer/products.mdx

This PR introduces changes to `Products` and `Channels` guides for the issues found in #564 
#812

Update products & channels

---

docs/developer/stock-allocation.mdx
versioned_docs/version-3.x/developer/stock-allocation.mdx

changed "Go here for more information" to "Learn more." 

---

docs/developer/community/zero-downtime-migrations.mdx
versioned_docs/version-3.x/developer/community/zero-downtime-migrations.mdx

Add missing `removing index` case and as well cover foreign key case.

New zero-downtime case examples

---

docs/developer/extending/apps/developing-apps/troubleshooting.mdx
versioned_docs/version-3.x/developer/extending/apps/developing-apps/troubleshooting.mdx

Added solution to the issue found on the Cloud instance

Add solutions to the CORS error on cloud instances

---

docs/api-usage/metadata.mdx
docs/developer/app-store/apps/crm.mdx
docs/developer/app-store/apps/taxes/avatax/overview.mdx
docs/developer/extending/apps/developing-apps/apps-patterns/persistence-with-metadata-manager.mdx
docs/overview/features.mdx
sidebars.js
vercel.json
versioned_docs/version-3.x/api-usage/metadata.mdx
versioned_docs/version-3.x/developer/app-store/apps/crm.mdx
versioned_docs/version-3.x/developer/app-store/apps/taxes/avatax/overview.mdx
versioned_docs/version-3.x/developer/extending/apps/developing-apps/apps-patterns/persistence-with-metadata-manager.mdx
versioned_docs/version-3.x/overview/features.mdx
versioned_sidebars/version-3.x-sidebars.json

Move Metadata to API Usage

---

docs/developer/app-store/apps/taxes/development.mdx
docs/developer/community/faq.mdx
docs/developer/extending/plugins/overview.mdx
docs/developer/products.mdx
versioned_docs/version-3.x/developer/app-store/apps/taxes/development.mdx
versioned_docs/version-3.x/developer/community/faq.mdx
versioned_docs/version-3.x/developer/extending/plugins/overview.mdx
versioned_docs/version-3.x/developer/products.mdx

Remove Vatlayer mentions

---

docs/developer/app-store/apps/adyen.mdx
docs/developer/app-store/apps/invoices.mdx
docs/developer/app-store/apps/stripe.mdx
docs/developer/checkout/overview.mdx
docs/developer/extending/payment-gateways.mdx
docs/developer/extending/plugins/overview.mdx
versioned_docs/version-3.x/developer/app-store/apps/adyen.mdx
versioned_docs/version-3.x/developer/app-store/apps/invoices.mdx
versioned_docs/version-3.x/developer/app-store/apps/stripe.mdx
versioned_docs/version-3.x/developer/checkout/overview.mdx
versioned_docs/version-3.x/developer/extending/payment-gateways.mdx
versioned_docs/version-3.x/developer/extending/plugins/overview.mdx

Mark payment plugins as legacy

---

docs/developer/extending/apps/local-app-development.mdx
versioned_docs/version-3.x/developer/extending/apps/local-app-development.mdx

Rel
https://github.com/saleor/saleor-platform/pull/296

Add information about Core setting that must be changed to develop apps

---

docs/setup/configuration.mdx

Added documentation for the `PUBLIC_URL` setting.
Related: https://github.com/saleor/saleor/pull/13841

Add `PUBLIC_URL` setting

---

docs/developer/bulks/bulk-orders.mdx

Documentation changes for: https://github.com/saleor/saleor/pull/14177

Update bulk order guide

---

docs/developer/community/contributing.mdx
versioned_docs/version-3.x/developer/community/contributing.mdx

Extend contribution guide with info how to handle changes in `PREVIEW_FEATURE` and to keep migrations reversible

Upgrade contribution guide

---

docs/developer/extending/webhooks/ip-addresses.mdx
sidebars.js
versioned_docs/version-3.x/developer/extending/webhooks/ip-addresses.mdx
versioned_sidebars/version-3.x-sidebars.json

Fixes https://github.com/saleor/saleor-docs/issues/1007

Add page about Saleor IP Addresses

---

docs/developer/extending/apps/architecture/communication-between-app-and-saleor.mdx
docs/developer/extending/webhooks/asynchronous-events.mdx

Documents changes implemented by https://github.com/saleor/saleor/pull/14566

Document time limits and retry strategies for HTTP webhooks

---

.github/workflows/update-stable-version.yml

Closes https://github.com/saleor/saleor-docs/issues/1027

Update community actions in `update-stable-version`

---

.github/workflows/update-cli-docs.yml
.github/workflows/update-stable-version.yml

Fixes https://github.com/saleor/saleor-docs/issues/1027

Prevent GH actions from overwriting PRs

---

docs/developer/app-store/apps/taxes/avatax/overview.mdx
docs/developer/app-store/apps/taxes/overview.mdx
versioned_docs/version-3.x/developer/app-store/apps/taxes/avatax/overview.mdx
versioned_docs/version-3.x/developer/app-store/apps/taxes/overview.mdx

rel: https://github.com/saleor/apps/pull/1189

Document customer code mapping in AvaTax integration

---

docs/developer/app-store/apps/adyen.mdx
versioned_docs/version-3.x/developer/app-store/apps/adyen.mdx

* Adds information on how to obtain various keys and config data

Improve Adyen configuration docs

---

docs/api-reference/payments/mutations/transaction-event-report.mdx
docs/api-reference/payments/mutations/transaction-process.mdx
docs/api-reference/payments/mutations/transaction-request-action.mdx
docs/api-reference/payments/mutations/transaction-request-refund-for-granted-refund.mdx
docs/api-reference/payments/mutations/transaction-update.mdx
docs/api-reference/payments/objects/transaction-item.mdx
versioned_docs/version-3.x/api-reference/payments/mutations/transaction-event-report.mdx
versioned_docs/version-3.x/api-reference/payments/mutations/transaction-process.mdx
versioned_docs/version-3.x/api-reference/payments/mutations/transaction-request-action.mdx
versioned_docs/version-3.x/api-reference/payments/mutations/transaction-request-refund-for-granted-refund.mdx
versioned_docs/version-3.x/api-reference/payments/mutations/transaction-update.mdx
versioned_docs/version-3.x/api-reference/payments/objects/transaction-item.mdx

Modified (both 3_X and canary)
- TransactionUpdate mutation
- TransactionRequestAction mutation
- TransactionProcess mutation
- TransactionEventReport mutation
- TransactionRequestRefundForGrantedRefund mutation
- TransactionItem type

Update docs on adding token to TransactionItem and related mutations

---

docs/developer/discounts/promotions.mdx

Documentation for https://github.com/saleor/saleor/pull/15259
Resolves https://github.com/saleor/saleor/issues/15226

Gift promotions

---

.vscode/settings.json
docs/developer/app-store/apps/taxes/overview.mdx
docs/developer/extending/apps/developing-apps/app-examples.mdx
versioned_docs/version-3.x/developer/app-store/apps/taxes/overview.mdx
versioned_docs/version-3.x/developer/extending/apps/developing-apps/app-examples.mdx

minor changes related to the Taxes App

Update Taxes App docs

---

docs/developer/extending/apps/installing-apps.mdx
docs/developer/taxes.mdx

https://github.com/saleor/saleor/pull/15292

Add taxes circuit break docs

---

sidebars.js
versioned_sidebars/version-3.x-sidebars.json

Add missing `Export voucher codes` page to export sidebar

Add missing `Export voucher codes` page to export sidebar

---

docs/developer/community/contributing.mdx
versioned_docs/version-3.x/developer/community/contributing.mdx

We did remove said files from Saleor repository

Remove outdated note regarding requirements.txt

---

docs/developer/community/faq.mdx
docs/developer/payments.mdx

This PR adds https://github.com/witoszekdev/dummy-payment-server to community resources

Add dummy payment app to community resources

---

docs/developer/taxes.mdx
versioned_docs/version-3.x/developer/taxes.mdx

https://github.com/saleor/saleor/pull/15433

Mention possibility to assign plugin to tax configuration

---

docs/developer/extending/apps/deploying-apps/preparing-for-production.mdx
docs/developer/extending/apps/deploying-apps/protecting-app.mdx
versioned_docs/version-3.x/developer/extending/apps/deploying-apps/preparing-for-production.mdx
versioned_docs/version-3.x/developer/extending/apps/deploying-apps/protecting-app.mdx

This PR removes empty pages from docs, that appeared when using serach

Remove empty pages from docs

---

docs/developer/extending/webhooks/synchronous-events/shipping.mdx
versioned_docs/version-3.x/developer/extending/webhooks/synchronous-events/shipping.mdx

This PR updates shipping API docs with:
* Mermaid diagram of requests flow
* Renames of deperacted entities
* Link to community resources 😄 
* Schema of required response from app
Ref SHOPX-213

Update shipping API docs

---

docs/developer/extending/webhooks/synchronous-events/shipping.mdx
versioned_docs/version-3.x/developer/extending/webhooks/synchronous-events/shipping.mdx

Document difference in shipping webhooks

---

docs/developer/checkout/address.mdx
versioned_docs/version-3.x/developer/checkout/address.mdx

This PR adds information what are collection points and mentions what are shipping methods in checkout guide.
Ref SHOPX-216

Document collection points

---

versioned_docs/version-3.x/developer/app-store/apps/adyen.mdx

Fixes https://github.com/saleor/saleor-docs/pull/1113 - adds the same update to Adyen App docs, to versioned docs

Add missing update to versioned docs form Adyen

---

docs/developer/extending/apps/developing-apps/apps-patterns/handling-external-webhooks.mdx
docs/developer/extending/apps/developing-apps/apps-patterns/persistence-with-metadata-manager.mdx
sidebars/apps-sidebar.js
versioned_docs/version-3.x/developer/extending/apps/developing-apps/apps-patterns/handling-external-webhooks.mdx
versioned_docs/version-3.x/developer/extending/apps/developing-apps/apps-patterns/persistence-with-metadata-manager.mdx
versioned_sidebars/version-3.x-sidebars.json

Changed the Apps docs structure according to https://www.notion.so/saleor/Apps-documentation-restructuring-2003680d9bc9436e81b799cfdbdce865?pvs=4

Restructure apps docs

---

docs/developer/extending/webhooks/synchronous-events/shipping.mdx
versioned_docs/version-3.x/developer/extending/webhooks/synchronous-events/shipping.mdx

Updates Shipping events information about fields that cause circular reference.
Code PR: https://github.com/saleor/saleor/pull/15636

Updates Shipping events information about fields that cause circular reference.

---

docusaurus.config.js
src/theme/Layout/index.js

Disable Sentry tracing

---

versioned_docs/version-3.x/developer/community/contributing.mdx

We no longer use `requirements_dev.txt`

Remove requirements.txt from contributing.mdx

---

docs/developer/community/contributing.mdx
docs/setup/windows.mdx
versioned_docs/version-3.x/setup/windows.mdx

Our installation instructions were incorrect and referred to unsupported files and commands.

Update installation commands

---

docs/developer/address.mdx
versioned_docs/version-3.x/developer/address.mdx

Related PR: https://github.com/saleor/saleor/pull/15877

Add info about valid address items extension.

---

docs/developer/checkout/address.mdx
versioned_docs/version-3.x/developer/checkout/address.mdx

Related PR: https://github.com/saleor/saleor/pull/15975
Ticket: https://linear.app/saleor/issue/SHOPX-568/switching-from-clickandcollect-to-shipping-automatically-pre-fills-the

Flow on how to go back from C&C to standard delivery method

---

docs/developer/taxes.mdx
versioned_docs/version-3.x/developer/taxes.mdx

Fix https://github.com/saleor/saleor-docs/issues/1058

Update the tax address hierarchy docs

---

docs/api-reference/orders/inputs/order-settings-update-input.mdx
versioned_docs/version-3.x/api-reference/orders/inputs/order-settings-update-input.mdx

Related changes: https://github.com/saleor/saleor/pull/15997

Update description for OrderSettingsUpdateInput.automaticallyConfirmAllNewOrders

---

.github/workflows/update-cli-docs.yml
.github/workflows/update-stable-version.yml

As versioning process is being modifed it's better to disable them until it's finished

Disable update-* workflows

---

docs/developer/app-store/apps/avatax/tax-codes.mdx
versioned_docs/version-3.x/developer/app-store/apps/avatax/tax-codes.mdx

Add information on how to configure tax-exempt products in AvaTax App
https://linear.app/saleor/issue/SHOPX-894/avatax-add-example-doc-how-to-make-tax-exempt

Add tax exemption section to AvaTax app

---

docs/developer/app-store/apps/smtp/configuration.mdx
docs/developer/app-store/apps/smtp/overview.mdx
versioned_docs/version-3.x/developer/app-store/apps/smtp/configuration.mdx
versioned_docs/version-3.x/developer/app-store/apps/smtp/overview.mdx

Added docs to upcoming change in the SMTP app
https://github.com/saleor/apps/pull/1453/files#diff-7b1a8aaaf9f890c6d484fc139996ad4d3ddb27b5674f82be52c718738ae56027R7

Update SMTP app docs to contain handlebars-helpers info

---

docs/developer/payment-status.mdx
sidebars.js
versioned_docs/version-3.x/developer/payment-status.mdx
versioned_sidebars/version-3.x-sidebars.json

rel: https://github.com/saleor/saleor-docs/pull/1018

Add payment status graph

---

docs/developer/order-expiration.mdx
sidebars.js
versioned_docs/version-3.x/developer/order-expiration.mdx
versioned_sidebars/version-3.x-sidebars.json

https://linear.app/saleor/issue/SHOPX-804/docs-order-expiration-and-deletion
https://github.com/saleor/saleor-docs/issues/1070

Add docs for order expiration

---

docs/developer/index.mdx
src/css/components/navbar.css
versioned_docs/version-3.x/developer/index.mdx

Added a small note as it was a bit confusing
Added highlight to selected section

Navigation nudges

---

docusaurus.config.js
package.json

Upgraded node.js to eliminate variables that could contribute to slow build time

Update to node 20

---

docs/developer/discounts/vouchers.mdx

Add info that vouchers are working on draft order since v3.19

Add info from which version vouchers are applicable on draft orders

---

docs/api-usage/authentication.mdx

The PR adds info about the login throttling mechanism, described in [this RFC](https://github.com/saleor/saleor/discussions/16201) and implemented in [this PR](https://github.com/saleor/saleor/pull/16219)

Add login throttling mechanism description.

---

docs/api-usage/prices.mdx

Make it clear what is the precision of returned prices.

Extend pricing page with the amount precision

---

docs/developer/checkout/overview.mdx
docs/index.mdx
sidebars/core-concepts.js

Brake down checkout into chapters

---

src/theme/DocSidebar/index.js

https://github.com/user-attachments/assets/2b5aae2e-7bfe-4b7d-b588-a8324bb5b47d

Scroll to chapter in sidebar

---

docs/developer/app-store/apps/adyen/overview.mdx

Add adyen features

---

docs/developer/checkout/overview.mdx

Added section in Checkout docs about completing them when total amount is 0

Add docs about checkouts with 0 amount

---

docs/developer/payments/payment-apps.mdx
docs/developer/payments/refunds.mdx
docs/developer/payments/transactions.mdx

Docs for https://github.com/saleor/saleor/pull/16410

Add info about amount precision in transaction API

---

docs/developer/app-store/apps/crm.mdx
docs/developer/app-store/apps/invoices.mdx
docs/developer/app-store/apps/segment.mdx

Update links to repos with example for CRM, Segment and Invoices apps

---

docs/developer/extending/apps/architecture/manifest.mdx

Nudge manifest

---

docs/developer/checkout/cookbook.mdx

Closes https://github.com/saleor/saleor-docs/issues/1292

Checkout cookbook

---

docs/developer/app-store/apps/adyen/storefront.mdx

This PR adds information about handling errors when requesting additional actions

Update Adyen app error handling docs

---

docs/developer/app-store/apps/adyen/architecture.mdx

Added notes how refund `lineItems` are handled depending on used refund type.

Add notes about Adyen App refunds logic

---

docs/developer/app-store/apps/avatax/configuration.mdx

Requires
- https://linear.app/saleor/issue/SHOPX-1122
- https://linear.app/saleor/issue/SHOPX-760
to be released (3.19, 3.20)

Update docs about new AvaTax discounts strategies

---

docs/developer/payments/lifecycle.mdx
docs/developer/payments/transactions.mdx

Describe changes introduced in https://github.com/saleor/saleor/pull/16688

Describe amount calculations for reporting an action with missing amount value

---

docusaurus.config.js

Change the Algolia Public API Key

---

docs/developer/payments/lifecycle.mdx

Adjust information about valid order of transaction event report.

Adjust information about valid order of transaction event report

---

docs/developer/app-store/apps/avatax/tax-codes.mdx
docs/developer/extending/apps/architecture/server-and-client-side-calls.mdx
docs/developer/gift-cards.mdx

Fixes #1052: consistent naming for AccessToken.
Fixes #859: mention remaining balance for gift cards
Fixes #887: added multi-line list formatting for the tax exemption doc

Misc fixes

---

docs/developer/discounts/examples.mdx
docs/developer/discounts/manual-discounts.mdx
docs/developer/discounts/overview.mdx
docs/developer/discounts/vouchers.mdx
docs/developer/extending/webhooks/synchronous-events/tax.mdx
docs/developer/price-calculation.mdx
sidebars/core-concepts.js

Internal issue: https://linear.app/saleor/issue/SHOPX-918
This PR:
1. describes how Saleor calculates prices
2. extends overview discount page
3. adds `Manual discounts` section
4. adds paragraph `Tax data validation` (https://linear.app/saleor/issue/SHOPX-1348)
5. adds a section with complex examples

Add `Price Calculation` section.

---

docs/developer/app-store/apps/adyen/configuration.mdx

I improved documentation of Adyen webhook

Add more detailed additional settings info to Adyen app configuration

---

docs/developer/app-store/apps/smtp/overview.mdx
docusaurus.config.js
src/theme/DocItem/Footer/index.js

Algolia crawling got broken by changes from yesterday

Revert broken crawler

---

docs/developer/price-calculation.mdx

Extend `Price calculation` page with assumptions regarding unit and total prices.

Add assumptions regarding the line unit and total price

---

docs/developer/payments/transactions.mdx

Describe how we match `pspRefereneces`

Add TransactionItem and  `TransactionEvents` `pspReference` Matching section on `Transactions` page

---

docs/developer/checkout/troubleshooting.mdx

Describe solutions for paid checkout not converted into an order.

Add `Resolving Paid Checkouts Not Converting to Orders` section to checkout troubleshooting

---

docs/developer/app-store/apps/adyen/migration-guides.mdx

Add release notes for changes in Adyen app release 1.4.0

Add changelog for upcoming Adyen app change

---

components/Icons/icons.jsx
docusaurus.config.js
sidebars.js
src/css/components/navbar.css
src/css/components/search.css

- feedback button moved to the sidebar 
- sign up link added to the navbar
- changed placement of the search field in the navbar

Add feedback icon and move things around in sidebar

---

docs/developer/app-store/apps/adyen/overview.mdx

Fixes applied to CR https://github.com/saleor/saleor-docs/pull/1415#pullrequestreview-2514094701 that was done after I merged PR

Improve data processing section

---

docs/upgrade-guides/core/3-20-to-3-21.mdx

Related PR: https://github.com/saleor/saleor/pull/17261

Update upgrade guide for changes regarding updating metadata in `trasactionUpdate`

---

docs/developer/app-store/apps/segment.mdx

* Changed a bit documentation so it reflect changes made to Segment app

Update docs about Segment

---

docs/developer/price-calculation.mdx

I found a mistake in the price calculation section

Fix mistakes in `Price Calculation` section

---

package-lock.json
package.json

Reverts saleor/saleor-docs#1450
It broke apps sidebar
We can add update one by one in other PR and we what package caused the problem 😄

Revert "Upgrade Docusaurus to 3.7.0"

---

docs/developer/extending/webhooks/synchronous-events/shipping.mdx
docs/upgrade-guides/core/3-20-to-3-21.mdx

Covers the: https://github.com/saleor/saleor/pull/17350

Add note about excluding shipping methods with different currency than checkout's currency

---

docs/upgrade-guides/core/3-20-to-3-21.mdx

Changed in: https://github.com/saleor/saleor/pull/17366/files#

Add info that external-shipping-method is no longer stored in privateMetadata

---

docs/developer/extending/webhooks/synchronous-events/shipping.mdx
docs/developer/extending/webhooks/synchronous-events/tax.mdx
docs/upgrade-guides/core/3-20-to-3-21.mdx

Related changes: https://github.com/saleor/saleor/pull/17431

Add info about blocking webhooks in order bulk queries

---

docs/developer/community/faq.mdx
docs/developer/community/support.mdx
src/theme/DocItem/Footer/index.js

https://github.com/saleor/saleor/discussions/17436

Replace mentions of GH discussions with discord

---

docs/developer/price-freeze-period.mdx
docs/upgrade-guides/core/3-20-to-3-21.mdx
sidebars/core-concepts.js

This PR covers changes introduced in https://github.com/saleor/saleor/pull/17160

Add `Price Freeze Period` section.

---

docs/developer/order/order-status.mdx

Based on #1486 from @rkashapov.

Fix linebreaks in order state diagram

---

docs/developer/checkout/api-guide.mdx
docs/developer/products/api.mdx

Tiny fixes that make the docs easier to parse

Small fixes for style consistency and clarification

---

docs/developer/order/order-fulfillment.mdx
docs/developer/order/order-fulfillments.mdx
sidebars/core-concepts.js

Docs for fulfillment lifecycle, possible API actions, settings, and edge cases
More information about returns and refunds and their impact on order fulfillment will be presented in a separate PR. Here I mainly wanted to describe the lifecycle, some basic operations and settings that influence fulfillments flow and stocks

Fulfillment docs

---

.cursor/rules/enforce-guidelines.mdc
.github/PULL_REQUEST_TEMPLATE.md
.gitignore
GUIDELINES.md

- Extended the guidelines
- Added cursor rule to enforce them

Extend "Writing Documentation" Guidelines

---

package-lock.json
package.json

Fix broken sidebar by deps pin

---

docusaurus.config.js

Replaces community announcementBar with Discord one

Replace Community banner with Discord

---

docs/developer/attributes/api.mdx
docs/developer/attributes/overview.mdx
docs/developer/products/configuration.mdx

Add info about Swatch and plain text attributes.
Clarify that warehouse must be assigned to variant and sales channel

Add info about swatch and plain text attributes

---

docs/api-reference/checkout/subscriptions/_category_.yml
docs/api-reference/checkout/subscriptions/checkout-created.mdx
docs/api-reference/checkout/subscriptions/checkout-fully-paid.mdx
docs/api-reference/checkout/subscriptions/checkout-metadata-updated.mdx
docs/api-reference/checkout/subscriptions/checkout-updated.mdx
docs/developer/extending/webhooks/subscription-webhook-payloads.mdx

Extending the filter section to include the events that will be attached by this PR: https://github.com/saleor/saleor/pull/17647

Update docs about possibility to filter over checkout events

---

docs/api-usage/prices.mdx

Add info about max price value on prices page.
Related PR: https://github.com/saleor/saleor/pull/17678

Update prices page with max price value

---

components/RecipeResourceGrid/index.jsx
components/RecipeResourceGrid/styles.module.css
docs/index.mdx
docs/recipes/click-and-collect.mdx
docs/recipes/custom-shipping.mdx
docs/recipes/digital-products.mdx
docs/recipes/extending-dashboard.mdx
docs/recipes/multi-region.mdx
docs/recipes/overview.mdx
sidebars/recipes.js

- change recipe order from alphabetical to popularity
- extract syles of resource list to separate component
- better icons

Small fixes for recipes

---

docusaurus.config.js

Another rotation of announcement bar to keep novelty of this section

Disable community announcement bar

---

docs/developer/app-store/apps/stripe/supported-payment-methods.mdx

Use admonition for warning in supported payment methods

Use admonition for warning in supported payment methods

---

docs/developer/shipping/shipping-method.mdx
docs/developer/taxes.mdx

Docs for https://github.com/saleor/saleor/pull/17726

Add note about weighted taxes

---

docs/developer/extending/apps/developing-apps/macaw-ui.mdx
src/theme/Mermaid/index.jsx
src/theme/Mermaid/styles.module.css

Add a way to zoom in mermaid charts

---

docs/upgrade-guides/core/3-20-to-3-21.mdx

Covers the changes added in https://github.com/saleor/saleor/pull/17753

Add details to the migration guide about changes to email input handling in checkout mutations

---

docusaurus.config.js

Hide community update

---

docs/developer/extending/webhooks/synchronous-events/overview.mdx

Related PR: https://github.com/saleor/saleor/pull/17760

Add info about json schemas

---

docs/developer/app-store/apps/adyen/migration-guides.mdx
docs/developer/app-store/apps/adyen/pci-dss.mdx
docs/developer/app-store/apps/adyen/storefront.mdx

Diagram: https://saleor-docs-git-pci-dss-adyen-saleorcommerce.vercel.app/developer/app-store/apps/adyen/pci-dss

Add PCI DSS for Adyen app

---

docs/developer/extending/apps/developing-apps/generating-types-for-sync-webhooks.mdx
sidebars/building-apps.js

Add new guide: How to generate TypeScript types from JSON schemas

---

docs/recipes/marketplace.mdx

Small changes in marketplace.mdx

Clarify the role of OIDC in marketplace authentication 

---

docs/developer/app-store/legacy-plugins/adyen.mdx

Diagram: https://saleor-docs-git-pci-dss-adyen-plugin-saleorcommerce.vercel.app/developer/app-store/legacy-plugins/adyen#pci-dss-compliance

Add PCI DSS for Adyen plugin

---

docs/developer/app-store/apps/product-feed.mdx

Fix Handlebars typo

---

docs/developer/app-store/apps/stripe/pci-dss.mdx
docs/developer/app-store/legacy-plugins/np-atobarai.mdx

Add PCI DSS for NP Atobarai & update Stripe app diagram

---

docs/developer/app-store/apps/product-feed.mdx

wait for https://github.com/saleor/apps/pull/1992

update product feed app

---

docs/api-usage/usage-limits.mdx
docs/upgrade-guides/core/3-21-to-3-22.mdx

Add info about increased query cost

---

docs/developer/bulks/bulk-orders.mdx

Closes https://github.com/saleor/saleor-docs/issues/1222

Add info on warehouse allocations for OrderBulkCreateOrderLineInput`

---

docs/developer/app-store/apps/stripe/storefront-integration.mdx

Fix Stripe app payment gateway id

---

docs/developer/ai.mdx

Fix mcp-graphql `SCHEMA` field configuration.
Fixes: #1642

Fix mcp-graphql SCHEMA field use

---

src/components/CopyMarkdownButton/index.jsx

Fixes "copy for LLM" in Safari

fix copy for llm in safari

---

docs/api-usage/authentication.mdx
docs/cloud/environment.mdx
docs/developer/extending/webhooks/creating.mdx
docs/developer/extending/webhooks/overview.mdx

- Add caution that when using SSO creating token fails https://saleor-docs-git-cxe-1069-saleorcommerce.vercel.app/api-usage/authentication#email-and-password
- How to access Saleor Dashboard from Cloud and that it's using SSO https://saleor-docs-git-cxe-1069-saleorcommerce.vercel.app/cloud/environment#accessing-your-environment
- Improve section for app authentication to add links to installing or creating app to obtain app token  https://saleor-docs-git-cxe-1069-saleorcommerce.vercel.app/api-usage/authentication#app-authentication
- Add info how to create local app via api and dashboard to be able to use it as reference https://saleor-docs-mt6jeb355-saleorcommerce.vercel.app/developer/extending/webhooks/creating#app-creation

Improve authentication docs

---

docs/developer/discounts/vouchers.mdx
docs/developer/products/api.mdx
docs/developer/products/configuration.mdx
docs/developer/products/overview.mdx

-  Add [categories and collections overview ](https://saleor-docs-git-cxe-1036-saleorcommerce.vercel.app/developer/products/overview#categories-and-collections)
- Add [categories and collections configuration](https://saleor-docs-git-cxe-1036-saleorcommerce.vercel.app/developer/products/configuration#collections-and-categories)
- Improve [readability of creating product via dashboard ](https://saleor-docs-git-cxe-1036-saleorcommerce.vercel.app/developer/products/configuration#creating-an-example-product)
- Link [business overview and API mutations](https://saleor-docs-git-cxe-1036-saleorcommerce.vercel.app/developer/products/api#create-products) to entities required before creating product via API
- Document that `voucher.code` [returns value form first …

Explain categories and collections

---

docs/api-usage/usage-limits.mdx
docs/upgrade-guides/core/3-21-to-3-22.mdx

Revert info about increased query cost #1631, 
Core: https://github.com/saleor/saleor/pull/18027

Revert info about increased query cost

---

docs/upgrade-guides/core/3-21-to-3-22.mdx

Documentation for https://github.com/saleor/saleor/pull/18028.

Document behaviour change for order with a zero total amount

---

docs/cloud/environment.mdx

Public Cloud documentation of the differences between the sandbox and production
https://saleor-docs-26mfqx8ly-saleorcommerce.vercel.app/cloud/environment

Sandbox vs Production Differences

---

docs/cloud/environment.mdx
docs/cloud/overview.mdx
docs/cloud/restricting-api-access.mdx

Give more info about projects 
Explain all available cloud options for environments

More details about cloud environments

---

docs/cloud/configuration.mdx
docs/cloud/overview.mdx
sidebars/cloud.js

Explain permissions, inviting staff, organization settings, and personal settings

Add Cloud Configuration

---

docs/developer/address.mdx
docs/developer/checkout/address.mdx
docs/developer/checkout/api-guide.mdx
docs/developer/checkout/cookbook.mdx
docs/developer/checkout/lifecycle.mdx
docs/developer/checkout/troubleshooting.mdx
docs/developer/gift-cards.mdx
docs/developer/order/address.mdx
docs/developer/order/order-expiration.mdx
docs/developer/order/order-fulfillment.mdx
docs/developer/order/order-to-checkout.mdx
docs/developer/stock/overview.mdx

I want to update the sample queries/mutations so that they always use variables.
First batch:
Checkout, orders, stocks, gift cards, and address

Improve graphql examples

---

docs/upgrade-guides/core/3-20-to-3-21.mdx

Add migration guide for `accountRegister`

---

docs/developer/extending/webhooks/troubleshooting.mdx
docs/upgrade-guides/core/3-21-to-3-22.mdx

Covers: https://github.com/saleor/saleor/pull/17996

Add info about webhooks when app is not active
