website/pages/en/404.js
website/pages/en/index.js
website/static/css/layout.css

This PR adds some styling to static pages, so they fit visually to the rest of the docs:

Tweak static pages layout

---

docs/customization/extensions.md
docs/customization/intro.md
docs/getting-started/configuration.md
docs/integrations/sentry.md
website/sidebars.json

Old docs had Extensions and Sentry pages updated sometime after I've moved all dev docs to Docusaurus. This PR re-adds those to new docs.

Add changes in dev docs made after initial devdocs sync

---

website/siteConfig.js
website/static/css/layout.css

This PR enables search on the docs:
Currently search bar is always aligned to the sidebar. If we want to align it to the content column, that would take some extra CSS-fu, so its up for @maarcingebala and @pwgryglak if we want to do it.

Enable search

---

website/static/css/layout.css

Some of our CSS selectors ended overzelous and in result has overrided the Algolia's branding in search results block. This PR fixes this.

Fix Algolia's branding not displaying correctly on search results

---

docs/api-reference.md
docs/index.md
website/package-lock.json
website/package.json
website/sidebars.json

This PR adds API Reference section. The reference was generated with [graphql-markdown](https://github.com/exogen/graphql-markdown) tool. It's not perfect, as the entire reference sits in a single file, but I think it's a good starting point.
To update the reference use the following command:
`npm run build-api-reference <schema>`
Example with Saleor running locally on default port:
`npm run build-api-reference http://localhost:8000/graphql/`

Add API reference

---

website/static/css/code-block-copy-button.css

As reported in  https://github.com/mirumee/saleor-docs/pull/55#issuecomment-539709428
сс @NyanKiyoshi

Remove copy button outline in Firefox

---

website/siteConfig.js

This tiny change encourages people to improve the page, and just usually in the docs there is a similar link.

Add link to edit document on GitHub

---

website/static/css/custom.css

Currently styles for buttons (edit button) with a green border  due the default theme style for Docusaurus. This PR overrides the default styles for the button to look like other buttons on docsite.
Before:
After:

Add unified button style

---

docs/advanced/managing-dependencies.md

Add option `--without-hashes` to commands generating requirements.
Closes #83

Add without-hashes option to poetry generate requirements commands

---

docs/getting-started/installation-linux.md
docs/getting-started/installation-macos.md
docs/getting-started/installation-windows.md

Updated installation guide to mention that Python 3.8 is required to run Saleor. Restructured MacOs installation guide to have the same structure as other guides for Windows and Linux.
Closes #98

Update Python installation notes

---

.gitignore
docs/api-reference.md
docs/api/intro-to-graphql.md
website/siteConfig.js
website/versioned_docs/version-2.9.0/api/intro-to-graphql.md

Changes in this PR:
- removed the instability note
- bumped API reference
- changed path to API docs in the navbar - now it's always linking to the "next" version even if you're on 2.9.0 docs
- updated .gitignore to ignore `.*` files (local configuration)

Remove instability note

---

website/siteConfig.js

Reverts last change of path to API section. It doesn't work with docs for 2.8 where this section was not available.

Revert path to API docs

---

docs/developer.mdx
docs/developer/users.mdx
website/sidebars.json

Add documentation for customer accounts API:
Part of #112 changes.

Document API for customer accounts

---

website/components/Chart/index.jsx

Fixes an exception during reloading of pages that contain charts (for example the Extending page).
Mermaid uses D3 internally but it serialized and deserializes its output, losing data binding in the process so when an existing node is encountered by D3 is trips over the lack of a `__data__` attribute. By using a unique ID each time we rerender we prevent D3 from ever seeing the existing structure.

Work around Mermaid's rerendering bug

---

docs/developer/running-saleor/s3.mdx

I just added the two environment variables AWS_QUERYSTRING_AUTH and AWS_QUERYSTRING_EXPIRE to the docs.

Adding Querystring settings to doc

---

docs/developer/community/faq.mdx

Add FAQ for `OSError: no library called "cairo" was found, no library called "libcairo-2" was found` error.

Add FAQ for no cairo library error

---

website/versioned_docs/version-2.10/developer/checkout.mdx
website/versioned_docs/version-2.9.0/api-process/check-out.md

There is a small mistake in `checkoutCreate` mutation, which was fixed for master (#147), but not for 2.9 and 2.10. 
This PR fixing the mistake on 2.9 and 2.10.

Update checkoutCreate mutation for 2.9 and 2.10

---

docs/developer/products.mdx

Add to sort section information about fields:
- `TYPE`
- `PUBLISHED`
- `PUBLICATION_DATE `

Add missing sort fields to docs

---

docs/developer/running-saleor/s3.mdx

- Update the link to CORS instructions from GCP to AWS docs
- Add instructions for CORS configuration when using the new S3 console (only allows JSON config)

Update S3 CORS instructions

---

docs/developer/extending/api/errors.mdx

In documentation related to extending errors, we have a missing step.

Add missing step in custom errors

---

docs/developer/extending/apps.mdx

Fix Apps command typo

---

docs/developer/products.mdx

Document the recently added `address` param for pricing fields.

Describe address parameter in pricing API

---

docs/developer/running-saleor/s3.mdx

Fixes #34
Misconfiguring access permissions is a common issue with deployments. Added short description and linked AWS docs.

Add S3 ACL description

---

docs/developer/community/support.mdx
website/versioned_docs/version-2.11/developer/community/support.mdx

Since spectrum is going into maintenance mode, we should direct all users to the Discussions

Direct community to the GitHub Discussions

---

website/src/css/theme.css

Fix code blocks whitespace

---

docs/developer/checkout.mdx

Update checkout section. Use `token` instead of `checkoutId` in checkout mutations as it's recommended way right now.

Use checkout token in checkout mutations instead of checkoutId

---

docs/developer/checkout.mdx

This PR expands checkout documentation with description of reservations feature and their behavior.
Preview: https://saleor-docs-git-checkout-stock-reservations-saleorcommerce.vercel.app/docs/3.0/developer/checkout#stock-reservations
Related: https://github.com/mirumee/saleor/pull/7589

Add reservations doc to checkout process

---

versioned_docs/version-2.9.0/getting-started/installation-macos.md

Command for PostgresSQL should specify the user of PostgresSQL. Since it default using `postgres `as username and the postgres-cli would use the username of the unix user to login (which normally won't be `postgres`) causing the command failed to execute.

Command for PostgresSQL should specify the user

---

docs/developer/extending/plugins.mdx

Hi! I think I found two little name mistakes in the extending plugins page

Fix little name errors

---

docs/developer/checkout.mdx

Currently the shown mutation is `ShippingAddressUpdate`, but the field used on the example is `billingAddress` instead of `shippingAddress`

Fix incorrect field value on ShippingAddressUpdate

---

versioned_docs/version-2.11/developer/running-saleor/s3.mdx

From now on, AWS S3 Buckets CORS configuration only accepts parameters as JSON.

Update CORS config to JSON

---

docs/developer/extending/apps/asynchronous-webhooks.mdx

I want to merge this because it adds a section to Apps webhook documentation about validating the `Saleor-Signature` header.
Preview: https://saleor-docs-3x9mu2e00-saleorcommerce.vercel.app/docs/3.x/developer/extending/apps/asynchronous-webhooks#validating-signature

Add section about validating Saleor webhook signature

---

docs/developer/running-saleor/gcs.mdx

[https://docs.saleor.io/docs/3.x/developer/running-saleor/gcs#environment-variables](https://docs.saleor.io/docs/3.x/developer/running-saleor/gcs#environment-variables)
Table contains entry ```GS_STORAGE_BUCKET_NAME``` as "The GCS bucket name to use for static files.".
The environment variable should be ```GS_BUCKET_NAME```.
- Changed the environment variable from ```GS_STORAGE_BUCKET_NAME``` to ```GS_BUCKET_NAME```.
- Change wording to better convey the environment variable required for either media or static file storage.

Fix environment variable used to store static files in Google Cloud Storage

---

docs/developer/extending/apps/synchronous-webhooks/tax-webhooks.mdx

- Fix incorrect ending a warning section
- Fix incorrect header markings
- Add more context to tax_rate field
- Fix sidebar:
Was:
After PR:

Clean up tax webhook docs

---

docs/developer/checkout.mdx

Shopping cart is a bigger basket on wheels, I think in this context the author meant `checkout`.

fix wording in cart models explanation

---

docs/developer/api-reference/enums/allocation-strategy-enum.mdx
docs/developer/api-reference/inputs/channel-create-input.mdx
docs/developer/api-reference/inputs/channel-update-input.mdx
docs/developer/api-reference/inputs/stock-settings-input.mdx
docs/developer/api-reference/mutations/channel-reorder-warehouses.mdx
docs/developer/api-reference/objects/channel-reorder-warehouses.mdx
docs/developer/api-reference/objects/channel.mdx
docs/developer/api-reference/objects/stock-settings.mdx
docs/developer/channels.mdx
docs/developer/stock-allocation.mdx

Docs regarding the following changes: https://github.com/saleor/saleor/pull/10416
- Explain the `allocation strategies`
- Update `channel` section - explain `channelReorderWarehouses`

Reordering warehouses within channel and allocation strategies

---

docs/developer/extending/apps/manifest.mdx

This PR fixes incorrect example of app's manifest. It should use `asyncEvents` and `syncEvents` properties instead of `events`, just like in `webhookCreate` mutation

Fix manifest example - use `asyncEvents` instead of `events`

---

src/theme/Layout/index.js

I noticed quite a lot of similar Sentry errors saying something along the lines of:
> ChunkLoadError: Loading chunk 26777 failed.
> (error: https://docs.saleor.io/assets/js/3f8f4758.9a9c897c.js)
It happened after the users clicked on any of the article navigation links.
I dug into it and to the best of my knowledge, this is what's happening:
1. The user goes to the page
2. We deploy a new version of the docs in the meantime (and we've had a lot of deploys in the last weeks)
3. The user clicks a link, trying to open a new article
4. The link will not work because it is tied to a JavaScript chunk that the user is no longer able to download ([because it was removed from the CDN](https://vercel.com/docs/concepts/edge-network/caching#cache-invalidation))
5. The error is being thrown
There are …

fix: :bug: reload the page on ChunkLoadError

---

docs/dashboard/customers.md

I want to merge this, because this PR adds a note in *Dashboard Manual > Customers* about filtering of stuff members.
It was confusing to me, because I couldn't add a customer with an email address that was used by a stuff member, and I couldn't find that customer in the list.

Add note about stuff members filtering in Dashboard Manual

---

docs/developer/users.mdx

Deprecated `accountErrors` causes this warning in mutations in [users](https://docs.saleor.io/docs/3.x/developer/users) page.
"This field will be removed in Saleor 4.0. Use errors field instead."

docs: replace deprecated accountErrors with errors

---

components/CardGrid/styles.module.css

This corrects the font weight for card grid card titles

Add missing font weight to card titles

---

docs/developer/checkout.mdx

Prettier indents the caution fence if it's part of the same paragraph.

Fix the caution section

---

docs/developer/discounts.mdx
sidebars.js

Add the `discounts` page explaining the basics of discounts.
The page should be extended later with:
- explanation of how to create a `sale` and `voucher`
- the `shipping` voucher example

Add discounts page

---

docs/upgrade-guides/3-11-to-3-12.mdx

Add info on how `checkout.discount` is changed in 3.12.
The changes for https://github.com/saleor/saleor/pull/12191

Update 3.12 upgrade guide for #12191

---

docs/developer/extending/apps/manifest.mdx

Add new fields `requiredSaleorVersion` and `author` to the App manifest description

Add `requiredSaleorVersion` and `author` fields to App manifest

---

docs/developer/taxes.mdx
sidebars.js

Add a page about new tax configuration, flat rates, dynamic taxes and tax exemption. Dynamic taxes could be extended into a more detail tutorial about creating tax apps, but it can be done separately.

Add tax docs

---

docs/developer/extending/apps/manifest.mdx

I want to highlight that the new `requiredSaleorVersion` and `author` App manifest fields will be respected starting from Saleor 3.13

Extend `requiredSaleorVersion` and `author` App manifest fields descriptions

---

docs/developer/discounts.mdx

Extend the discounts page with examples of completing checkout with voucher and product on sale.

Extend discounts page with example of checkout completing

---

.github/workflows/update-reference.yml
docs/api-reference/queries/product.mdx
docs/api-reference/queries/products.mdx
examples/api-reference/queries/product.mdx
examples/api-reference/queries/products.mdx
package-lock.json
package.json
scripts/inject-examples.ts

This PR introduces the `Examples` section to the API reference pages. 
Example section is put in the generated API reference page using [Markdown imports](https://docusaurus.io/docs/markdown-features/react#importing-markdown). The import is put into the page with the use of the `inject-examples` script. The script takes the corresponding file with examples and imports into the page.  
The `update-reference` workflow has been modified to do that.
Pages with examples are stored in a separate `examples` folder. 
This folder structure should be the same as the one generated with the [GraphQL-Markdown](https://graphql-markdown.github.io/) `api-reference`. 
1. Create a new file in the `examples` folder with the same path as the API reference page you are documenting.
1. Import the file to the …

Inject examples to api-reference

---

docs/setup/configuration.mdx

I want to remove the `CREATE_IMAGES_ON_DEMAND` paragraph from the configuration as it is no longer relevant after we switched from `django-versatileimagefield` to the custom thumbnails mechanism.

Drop django-versatileimagefield settings

---

examples/snippets/collections/CollectionAddProduct.mutation.graphql
examples/snippets/collections/CollectionList.query.graphql
examples/snippets/collections/CollectionListWithProducts.query.graphql
examples/snippets/products/ProductByID.query.graphql
examples/snippets/products/ProductByIDwithVariants.query.graphql
examples/snippets/products/SimpleProductList.query.graphql

This PR adds the snippets directory that will be used to display the examples in the built-in GraphiQL playground when in Saleor Dashboard

Add snippets for the examples section in GraphiQL

---

docs/api-usage/pagination.mdx

Adding missing information on how many objects could be fetched by on query.

Add currently set max to field descriptions for first and last 

---

src/css/theme.css

Closes #656 
The problem is coming because of the `filter` present on navbar. There's a discussion regarding this on Docusaurus Github [Issue #6996](https://github.com/facebook/docusaurus/issues/6996)

Fix: sidebar not coming on mobile devices

---

docs/upgrade-guides/3-13-to-3-14.mdx

I want to merge this change because when Saleor `3.13.8`, with new celery data migrations, is released, we need to recommend migrations to this version before 3.14 to follow the zero-downtime strategy.

Update 3.13 to 3.14 upgrade guide

---

docs/upgrade-guides/3-13-to-3-14.mdx

Upgrading guide from 3.13 to 3.14 after refactor price calculation for Sales.

Upgrading guide from 3.13 to 3.14 after refactor price calculation for Sales.

---

docs/developer/extending/apps/synchronous-webhooks/transaction-webhooks.mdx

Covers the bug reported here: https://github.com/saleor/saleor/issues/12787

Add note about `actions` field in the webhook response for transactions

---

docusaurus.config.js

DOCSEARCH can use only [Search API Parameters](https://www.algolia.com/doc/api-reference/search-api-parameters/)

Remove searchParameters from Algolia

---

docs/upgrade-guides/3-13-to-3-14.mdx

Upgrade update guide for 3.14 to contain the last 3.13 patch with the required migrations to migrate without downtime

Update upgrade guide for 3.14

---

docs/setup/docker-compose.mdx

It's not clear how to access dashboard after the docker based setup has been performed so I added a sentence about that.

Add information on where to look for a local dashboard instance

---

docs/developer/extending/apps/developing-apps/app-template.mdx
docs/developer/extending/apps/quickstart.mdx

We received feedback from @aniav that it's not clear enough that JavaScript isn't the only option to create Saleor apps.
- I split up the "Quickstart" article into sections "JavaScript" and "Other languages", while making it clear there is an existing app ecosystem in JS.
- Added a paragraph about the app solutions in Python, linking to Mirumee's [`saleor-app-framework-python`](https://github.com/mirumee/saleor-app-framework-python).

apps docs improvement

---

docs/developer/app-store/apps/emails-and-messages/overview.mdx
docs/developer/app-store/apps/emails-and-messages/sendgrid.mdx
docs/developer/app-store/apps/emails-and-messages/smtp.mdx
docs/developer/app-store/apps/emails-and-messages/troubleshooting.mdx
docs/developer/app-store/apps/overview.mdx
docs/developer/app-store/development.mdx
sidebars.js

- Add Emails and Messages documentation
- Sort app cards on the overview page

Add documentation for Emails and Messages app

---

docs/developer/app-store/apps/emails-and-messages/smtp.mdx
docs/developer/app-store/apps/emails-and-messages/troubleshooting.mdx

Added instructions for easy-to-miss mistake - using the wrong sender address.

EAM App: Mention using a proper sender address

---

docs/developer/metadata.mdx

We can link to the ObjectWithMetadata type for the list of all supported items, which is easier to maintain than updating the list manually.

Update list of supported metadata objects

---

components/AppMetadata/AppMetadata.module.css
components/AppMetadata/AppMetadata.tsx
docs/developer/app-store/apps/invoices.mdx
sidebars.js

This adds missing functional docs for Invoices app, based on the [template](https://github.com/saleor/saleor-docs/pull/829)

Add invoices docs

---

scripts/create-storefront-schema.ts

As pointed out by @korycins the storefront schema generation failed while new Unions have been added to the schema.

Handle more definitions in storefront schema

---

docs/developer/app-store/apps/taxes/architecture.mdx
docs/developer/app-store/apps/taxes/overview.mdx
versioned_docs/version-3.x/developer/app-store/apps/taxes/architecture.mdx
versioned_docs/version-3.x/developer/app-store/apps/taxes/overview.mdx

As we completed the migration, I removed all the notion of it in the docs.
see: https://github.com/saleor/apps/pull/916

docs: :memo: remove notion of migration

---

docs/developer/extending/webhooks/synchronous-events/overview.mdx
docs/developer/extending/webhooks/synchronous-events/stored-payment-method.mdx
docs/developer/payments.mdx
sidebars.js

It adds:
- section to payments: `stored-payment-methods`
- description of the list-stored-payment-methods webhook
More details can be found [here](https://github.com/saleor/saleor/issues/13384)

[programmatic-payments] Stored payment methods

---

docs/upgrade-guides/notify-user-deprecation.mdx
sidebars.js

Docs for https://github.com/saleor/saleor/issues/13803
I'll see if I can add links to API reference for subscription types in this PR or later, I think some of the subscription types are not grouped correctly.

Add migration guide for NOTIFY_USER

---

docusaurus.config.js

With the changes to the Algolia Crawler, the default value is not needed.

Remove rank medatada from config

---

versioned_docs/version-3.x/developer/payments.mdx

One approach is deprecated, but there are three nevertheless

Fix stylistic mistakes in payments docs

---

docs/setup/configuration.mdx

This adds documentation for the new IP filtering feature of v3.16 https://github.com/saleor/saleor/pull/13891.

Add docs for IP filtering feature

---

src/theme/CodeBlock/Content/Element.js
src/theme/CodeBlock/Content/String.js
src/theme/CodeBlock/Content/styles.module.css

This PR intoduces expandable/collapslible CodeBlock/Content. It's enabled when the code contains more than 18 lines.
#923

Expandable/collapslible CodeBlock/Content

---

docs/developer/extending/apps/architecture/apl.mdx
versioned_docs/version-3.x/developer/extending/apps/architecture/apl.mdx

This PR updates list of available APLs in https://docs.saleor.io/docs/3.x/developer/extending/apps/architecture/apl#available-apl-clients
It also updates dead links in that docs page

Update outdated APL docs 

---

versioned_docs/version-3.x/cli/commands/environment.mdx
versioned_docs/version-3.x/cli/commands/storefront.mdx
versioned_docs/version-3.x/cli/overview.mdx

This PR updates CLI docs in the `3.x` version after CLI v1.39.0 release https://github.com/saleor/cli/releases/tag/1.39.0

Update CLI docs in `3.x`

---

docs/developer/bulks/bulk-orders.mdx
docs/developer/discounts/vouchers.mdx

It adds chapter about voucher usage in draft orders.
RFC: https://github.com/saleor/saleor/issues/13713

Update docs about voucher usage with draft orders.

---

docs/developer/app-store/apps/TEMPLATE.mdx
docs/developer/app-store/apps/cms.mdx
docs/developer/app-store/apps/crm.mdx
docs/developer/app-store/apps/emails-and-messages/overview.mdx
docs/developer/app-store/apps/invoices.mdx
docs/developer/app-store/apps/search.mdx
docs/developer/app-store/apps/segment.mdx
docs/developer/app-store/apps/taxes/overview.mdx
versioned_docs/version-3.x/developer/app-store/apps/TEMPLATE.mdx
versioned_docs/version-3.x/developer/app-store/apps/cms.mdx
versioned_docs/version-3.x/developer/app-store/apps/crm.mdx
versioned_docs/version-3.x/developer/app-store/apps/emails-and-messages/overview.mdx
versioned_docs/version-3.x/developer/app-store/apps/invoices.mdx
versioned_docs/version-3.x/developer/app-store/apps/search.mdx
versioned_docs/version-3.x/developer/app-store/apps/segment.mdx
versioned_docs/version-3.x/developer/app-store/apps/taxes/overview.mdx

We are rebuilding how roadmaps will be exposed. The roadmap links from apps in docs didn't reflect actual plans and were outdated. To avoid confusion, they are removed.
In the future new roadmaps can be linked using the same component

Remove roadmap links from docs

---

docs/developer/app-store/apps/adyen.mdx

This PR adds information about timeout (5s) for `TRANSACTION_INITIALIZE_SESSION` webhook for Adyen app.
Related ticket: https://linear.app/saleor/issue/SHOPX-138/update-documentation-with-new-timeout

Add docs about TRANSACTION_INITIALIZE_SESSION timeout in Adyen app

---

docusaurus.config.js

It adds GTM setup to the config to use a common container among saleor.io subdomains

Add GTM container to config

---

docs/developer/app-store/apps/adyen.mdx
versioned_docs/version-3.x/developer/app-store/apps/adyen.mdx

Fixes https://github.com/saleor/saleor-docs/pull/1100 - YouTube iframe didn't load correctly due to using `?watch` link instead of `/embed`

Fix issues with YouTube iframe

---

docs/developer/extending/apps/developing-apps/app-sdk/api-handlers.mdx
docs/developer/extending/apps/developing-apps/app-sdk/saleor-webhook.mdx

As we have v0.50.0 with new `schemaVersion` I added docs as well: https://github.com/saleor/app-sdk/releases/tag/v0.50.0

Update app-sdk guide with schema version field

---

docs/developer/extending/apps/developing-apps/macaw-ui.mdx
sidebars/apps-sidebar.js
versioned_docs/version-3.x/developer/extending/apps/developing-apps/macaw-ui.mdx
versioned_sidebars/version-3.x-sidebars.json

Added new guide under:
* https://saleor-docs-git-add-macaw-ui-docs-saleorcommerce.vercel.app/docs/3.x/developer/extending/apps/developing-apps/macaw-ui

Add MacawUI docs

---

docs/cloud.mdx
docs/restricting-api-access.mdx
sidebars.js
versioned_docs/version-3.x/cloud.mdx
versioned_docs/version-3.x/restricting-api-access.mdx
versioned_sidebars/version-3.x-sidebars.json

**Context**:
We often get questions about how our Cloud users can restrict access to Saleor API. This article goes through the possible options and describes an example use case.
**Preview:** https://saleor-docs-git-restrict-api-access-saleorcommerce.vercel.app/docs/3.x/restricting-api-access

Restricting Saleor Cloud API access article

---

docs/developer/payments.mdx

Add a chapter related to `OrderGrantedRefund`. 
It also includes the scope of changes described in RFC: https://github.com/saleor/saleor/discussions/15458
The PR with mentioned changes: https://github.com/saleor/saleor/pull/15590

Provide docs for order-granted-refund

---

vercel.json

We identified that indexing the canary version impacts search results in a way we want to avoid. The main docs people should be landing on are the current released version, not the next version we plan to release. This PR is adding a change to stop indexing canary through Vercel directives.

Stop indexing canary docs

---

docusaurus.config.js

They are mostly useless (i.e. they cannot be used to navigate) and add visual noise to the page header.

Disable breadcrumbs in docs

---

docs/setup/windows.mdx
versioned_docs/version-3.x/setup/windows.mdx

This changes the PostgreSQL version from v12 to v15 in the Windows manual (non-containerized) installation instructions as we no longer actively maintain v12, only v15.
Acts as a follow-up to:
- https://github.com/saleor/saleor-platform/pull/309
- https://github.com/saleor/saleor/pull/16055

Update PostgreSQL version in Windows installation instructions

---

components/CardGrid/styles.module.css

Without shadows cards are more unified to the rest of Saleor brand

Remove shadows from cards

---

docs/developer/extending/webhooks/synchronous-events/shipping.mdx
versioned_docs/version-3.x/developer/extending/webhooks/synchronous-events/shipping.mdx

Add info on extended fields from external shipping method response that are parsed by Saleor. 
It documents changes from [15935](https://github.com/saleor/saleor/pull/15935)

Add additional info on external shipping method response fields

---

docs/api-usage/external-references.mdx
docs/upgrade-guides/3-18-to-3-19.mdx
versioned_docs/version-3.x/api-usage/external-references.mdx
versioned_docs/version-3.x/upgrade-guides/3-18-to-3-19.mdx

This PR introduces the section for `externalReference`. It also extends the migration-guide about using `externalReference` without proper permissions. 
> [!NOTE]  
> ~After applying review comments, I will also move the changes to versioned-docs~ Done!

Add info about externalReferences

---

docs/developer/discounts/vouchers.mdx

Update a paragraph about `Voucher usage in draft orders` to not mislead users since when the vouchers in draft orders are available.

Update a paragraph about `Voucher usage in draft orders`

---

docs/developer/discounts/vouchers.mdx

Update a paragraph about `Voucher usage in draft orders` to not mislead users since when the vouchers in draft orders are available.
Port of https://github.com/saleor/saleor-docs/pull/1210

Update a paragraph about Voucher usage in draft orders

---

docs/developer/discounts/vouchers.mdx

Adding some additional information about voucher usage and correct voucher types, as currently, it looks like only `PERCENTAGE` vouchers have options `ENTIRE ORDER` and `SPECIFIC PRODUCT`. Recently, there was also a question how to apply voucher to draft order.

Update voucher section

---

docs/developer/extending/apps/building-payment-app.mdx
package-lock.json
sidebars/building-apps.js

The preview is here: https://saleor-docs-git-payment-app-guide-saleorcommerce.vercel.app/docs/developer/extending/apps/building-payment-app

Add Payment App Tutorial

---

docs/developer/payments.mdx

This PR removes mentions of old dummy-payment-server as community resource, and adds links to new Dummy Payment App

Update dummy app links

---

docs/developer/checkout/order-status.mdx
package-lock.json

This change updates mermaid charts for order status now including effects of `orderFulfillmentCancel` mutation, also adding info how returns and fulfillment cancelations affect stock

Add information about stocks & fulfillment cancelations

---

components/Permissions/styles.module.css

Permission blocks look ambiguous as they have equal proximity to the bottom row 
Before:
After:

Nest permissions visually for clarity

---

docs/developer/extending/apps/building-payment-app.mdx
docs/developer/extending/webhooks/synchronous-events/transaction.mdx
docs/developer/payments/payment-apps.mdx
docs/developer/payments/transactions.mdx

While going through the tutorial, I added some optimizations to the content:
* Linked chapters together
* Added prerequisite reading as it is better that the reader first understands the payment APIs usage before building them. This removes the additional context required
* Made some sentences to be more concise 
* Change slightly the order of the content for fluidity
Next step suggestions:
We can extract the next parts and present them as a separate repo for reference, as most of the tutorial can be technology agnostic, making it appealing to a wider audience. The next js parts are quite small so we can leave out specifics in the README of the repository.

Payment nudges

---

docs/developer/app-store/legacy-plugins/stripe.mdx

This plugin is not deprecated at this moment.
Link to the Stripe App was also broken

Remove stripe plugin deprecation note

---

docs/developer/payments/refunds.mdx

Extend the payment refunds page with `Total remaining grant calculations` section.
Related to https://github.com/saleor/saleor/pull/16486

Update payment refunds page

---

docs/developer/extending/webhooks/synchronous-events/transaction.mdx

Update the docs according to changes introduced in https://github.com/saleor/saleor/pull/16181.
For some webhooks responses, the `pspReference` becomes optional.

Adjust transaction page

---

docs/developer/app-store/apps/adyen/overview.mdx

Improved description in Adyen app assumptions:
- app doesn't **always** return `pspReference` for XX_FAILURE responses, only when there wasn't a `pspReference` in a response from Adyen or an error was caused by internal app error handling
- app returns `XX_ACTION_REQUIRED` when there is no `pspReference` in the response from Adyen, response with `action` object might include a `pspReference` and it might be mapped to other response type

Improve description in Adyen app assumptions

---

docs/upgrade-guides/2-11-to-3-0.mdx
docs/upgrade-guides/3-0-to-3-1.mdx
docs/upgrade-guides/3-1-to-3-2.mdx
docs/upgrade-guides/3-11-to-3-12.mdx
docs/upgrade-guides/3-12-to-3-13.mdx
docs/upgrade-guides/3-13-to-3-14.mdx
docs/upgrade-guides/3-16-to-3-17.mdx
docs/upgrade-guides/3-17-to-3-18.mdx
docs/upgrade-guides/3-18-to-3-19.mdx
docs/upgrade-guides/3-20-to-3-21.mdx
docs/upgrade-guides/3-5-to-3-6.mdx
docs/upgrade-guides/notify-user-deprecation.mdx

Related Core PR: https://github.com/saleor/saleor/pull/16511
In 3.20 we deprecate `perform_mutation` plugin method and we'll remove it in Saleor 3.21.

Add info about deprecating manager.perform_mutation

---

docs/api-reference/miscellaneous/subscriptions/draft-order-created.mdx
docs/api-reference/miscellaneous/subscriptions/draft-order-deleted.mdx
docs/api-reference/miscellaneous/subscriptions/draft-order-updated.mdx
docs/api-reference/miscellaneous/subscriptions/order-bulk-created.mdx
docs/api-reference/miscellaneous/subscriptions/order-cancelled.mdx
docs/api-reference/miscellaneous/subscriptions/order-confirmed.mdx
docs/api-reference/miscellaneous/subscriptions/order-created.mdx
docs/api-reference/miscellaneous/subscriptions/order-expired.mdx
docs/api-reference/miscellaneous/subscriptions/order-fulfilled.mdx
docs/api-reference/miscellaneous/subscriptions/order-fully-paid.mdx
docs/api-reference/miscellaneous/subscriptions/order-fully-refunded.mdx
docs/api-reference/miscellaneous/subscriptions/order-metadata-updated.mdx
docs/api-reference/miscellaneous/subscriptions/order-paid.mdx
docs/api-reference/miscellaneous/subscriptions/order-refunded.mdx
docs/api-reference/miscellaneous/subscriptions/order-updated.mdx
docs/developer/extending/webhooks/subscription-webhook-payloads.mdx

The PR adds sections related to the filterable subscription webhooks that will be introduced in this PRs:
https://github.com/saleor/saleor/pull/16323
https://github.com/saleor/saleor/pull/16327
(The feature will be ported to 3.20)

Add section about filterable webhook subscription

---

docs/developer/app-store/legacy-plugins/adyen.mdx
docs/developer/app-store/legacy-plugins/np-atobarai.mdx
docs/developer/app-store/plugins/stripe.mdx
docs/developer/checkout/lifecycle.mdx

- Add info on potentially overcharged orders
- Add info that `amount` in `checkoutPaymentCreate` must be equal to `checkout.totalPrice`

Add info on potentially overcharged orders

---

docs/developer/app-store/apps/adyen/storefront.mdx

Adyen docs should explain that the App can't create 0 amount transactions.
https://linear.app/saleor/issue/SHOPX-1292/document-free-order-case-in-adyen-app-dosc

Add info about handling free orders with Adyen app

---

.github/workflows/test.yml

For now there is no better solution and I'd just like the builds to start working again

Fix broken QA build because the docuactions repo doesn't exist

---

docs/developer/checkout/cookbook.mdx
docs/developer/payments/lifecycle.mdx
docs/developer/payments/transactions.mdx

- Docs for https://github.com/saleor/saleor/pull/16782 (Should be merged together)
- Explain how `authorizeStatus` and `chargeStatus` work (resolves https://github.com/saleor/saleor-docs/issues/1010)

Explain automatic checkout completion option

---

docs/developer/app-store/apps/adyen/overview.mdx
docs/upgrade-guides/3-15-to-3-16.mdx

Added docs about `customerIpAddress` usage in Adyen app and migration guide for Saleor 3.15 -> 3.16 that mention this field.
> [!NOTE]
> Currently this field is not used by Adyen App, it will be re-enabled in future releases

Add note about IP address in adyen and add migration guide

---

docs/developer/payments/transactions.mdx
docs/upgrade-guides/core/3-19-to-3-20.mdx

Extend the docs regarding `automatic checkout completion` - add an info that the checkout will not be automatically completed when any validation error occurs. Explain how to check the problems on checkout.
Related PR: https://github.com/saleor/saleor/pull/16941

Extend automatic checkout completion with info that the checkout will not be completed if any validation error occurs

---

docusaurus.config.js

https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics
No package.json has to be modified since this plugin is part of another bundle.
The plugin is marked as deprecated and outdated, it has to be turned off.
After the merge well check if GTM integration is enough or we'll need to activate updated plugin.

Turn off deprecated GA plugin

---

docusaurus.config.js

The GTM tag id has been added to the deployment settings and will be enabled only on production builds to prevent sending events from test deployments.

Load GTM ID from the environment variable.

---

docs/developer/extending/webhooks/synchronous-events/transaction.mdx
docs/developer/payments/transactions.mdx

Make clear that any message above 512 characters reported for transaction event, will be truncated.

Inform about event report message limit

---

.github/workflows/check-spelling.yml
package-lock.json
package.json

When running the docs inside containers (specifically with volumes), the docs would fail to build with errors such as:
```
[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at: http://localhost:5000/
× Module not found: Can't resolve '/app/src/css/theme.css' in '/app/.docusaurus'
╭─[5:4]
3 │     require("/app/node_modules/@docusaurus/theme-classic/lib/prism-include-languages"),
4 │     require("/app/node_modules/@docusaurus/theme-classic/lib/nprogress"),
5 │     require("/app/src/css/theme.css")
·     ─────────────────────────────────
6 │ ];
╰────
[...]
× Cannot find module '@generated/site-storage' for matched aliased key '@generated'
[...]
client (Rspack 1.1.1) compiled with 34 errors
```
This commit fixes the issue by upgrading `@rspack/core` to v1.1.2 …

Fix build errors on container volumes

---

README.md

This fixes the link to the anchor to the docusaurus documentation section (issue introduced by 41199b2428293f1a6476585ecbea87562d4f94be)

fix: invalid anchor to docusaurus section in README.md

---

README.md

The README.md was referencing `sidebar.js` which is a non-existent file, instead it should be `sidebars.js`

fix: invalid filename for docs to modify sidebars in readme

---

docs/developer/payments/lifecycle.mdx
docs/developer/payments/transactions.mdx

Extend `Transaction event types` with `AUTHORIZATION_ACTION_REQUIRED`, `CHARGE_ACTION_REQUIRED` and `INFO`.

Extend Transaction event types section with `*_ACTION_REQUIRED` events

---

components/Icons/icons.jsx
docs/security/index.mdx
sidebars.js

This adds a 'Security' section, the intent of this page is to provide details about security features and design choices.
For now, it only documents the IP address filtering feature and other hardening we have around outgoing traffic. In the future, we may want to expand it further to provide details such as rate-limiting, and self-hosting best-practices.
Internal task: https://linear.app/saleor/issue/SEC-63/
Preview of the changes (@ Vercel): https://saleor-docs-git-docs-saleoradd-security-i-f94229-saleorcommerce.vercel.app/security/

docs: add security section

---

docs/api-usage/authentication.mdx
docs/developer/app-store/plugins/oidc.mdx

This change adds information about OIDC plugin limitation - as of current implementation, it is not possible to change e-mail address while preserving identity.

Add OIDC plugin limitations

---

docs/developer/bulks/bulk-orders.mdx

This change adds a warning in bulk order import article, explaining to use `IGNORE_FAILED` error policy if an user wants to create orders with product variants which were deleted from Saleor database.

Add bulk order import warning for deleted variants

---

docs/developer/app-store/apps/adyen/migration-guides.mdx

- **Add release notes for upcoming Adyen release**
- **Improve wording**

Add release notes for Adyen release

---

docusaurus.config.js

Meta description contains a lot of duplicates specifically when object and mutation have the same name. This change adds a prefix in meta description to make SEO mechanics happy.

Change how meta description is generated to avoid duplicates

---

docs/developer/discounts/vouchers.mdx

This PR clarifies, that `applyOncePerOrder` voucher reduces the value of a single unit, and not the entire line

Enhance `applyOncePerOrder` voucher behaviour description

---

docs/developer/order/overview.mdx
sidebars/core-concepts.js

I am adding an overview-type doc for orders since we don't have one. Main goal is to explain what an order is and point to existing resources

feat: add orders overview doc

---

docs/developer/discounts/displaying-catalogue-discounts.mdx
docs/developer/discounts/promotions.mdx
sidebars/core-concepts.js

In https://github.com/saleor/saleor-docs/pull/1432 there was a file not assigned to sidebar that got merged. I have added it to sidebar and changed the name to represent what it does.

Arrange docs in discounts

---

docs/developer/checkout/lifecycle.mdx
docs/developer/discounts/promotions.mdx
docs/developer/extending/webhooks/synchronous-events/transaction.mdx
docs/developer/order/order-expiration.mdx
docs/developer/payments/transactions.mdx
docs/developer/running-saleor/task-queue.mdx

We don't need to remind people that electricity is needed for code to run. Also tried to clarify that Celery needs to be deployed.

Make it clear that Celery is not optional

---

docs/api-usage/metadata.mdx

This adds a warning to inform developers to not store sensitive data in metadata, especially not financial information that may subject to PCI DSS regulation.

docs: add notice to not store sensitive data in metadata

---

docs/developer/app-store/plugins/oidc.mdx

Add info about all possible scopes for OAuth

---

docs/upgrade-guides/core/3-20-to-3-21.mdx

Update of upgrade guide for https://github.com/saleor/saleor/pull/17532 and https://github.com/saleor/saleor/pull/17507

Update upgrade guide - `DraftOrderUpdate` and `OrderUpdate` do not call webhooks anymore if nothing changed

---

docs/upgrade-guides/core/3-20-to-3-21.mdx

Adjust the upgrade guide for the following changes: https://github.com/saleor/saleor/pull/17635

Adjust upgrade guide for making transactionId in OrderGrantRefundCreateInput required

---

docs/upgrade-guides/core/3-20-to-3-21.mdx

Covers the changes introduced in:
https://github.com/saleor/saleor/pull/17587
& https://github.com/saleor/saleor/pull/17622

Add migration guide for propagating line level voucher discount

---

docusaurus.config.js

https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap
I'm on a hunt for Search Console issues. Our sitemap format was not compatible with current recommendations, which will be fixed by this PR

Sitemap improvements: add modification date; remove priority and change frequency

---

docs/upgrade-guides/core/3-20-to-3-21.mdx

The pull request https://github.com/saleor/saleor/pull/17660 renamed the environment variable `GS_MEDIA_BUCKET_NAME` for the GCP private storage bucket to `GS_MEDIA_PRIVATE_BUCKET_NAME` but wasn't documented as a breaking change.
Related PRs:
- https://github.com/saleor/saleor/pull/17660 (breaking change)
- https://github.com/saleor/saleor/pull/17671 (changelogs)

Upgrade guide: add instructions for GCP breaking change

---

docs/developer/app-store/plugins/oidc.mdx
docs/developer/order/draft-order.mdx
docs/developer/order/order-status.mdx
sidebars/core-concepts.js

Explain draft orders use case 
Update Order status graph based on changes introduced in https://linear.app/saleor/issue/BCK-456/use-automaticallyconfirmallneworders-with-draft-orders
Fix graph in OIDC docs 
Build: https://saleor-docs-git-cxe-884-draft-orders-saleorcommerce.vercel.app/developer/order/draft-order

Add draft orders overview

---

docs/api-usage/filtering.mdx

Explain what is the difference between `filter` and `where` option.
New paragraph:
https://saleor-docs-git-extend-filtering-page-saleorcommerce.vercel.app/api-usage/filtering#filter-vs-where-filtering

Extend filtering section - add filter vs where section

---

docs/developer/app-store/apps/adyen/storefront.mdx

This PR documents changes after fixing a bug with resolving amount, when creating Adyen Order.
Previously it was not accepting amount, it was always using checkout total.
The docs now explain how it works and how should be implemented

Document changes with amount resolving

---

scripts/highlight.js

Bump the number of the unreleased version, which can be displayed in the API reference.

Bump unreleased version

---

components/Chapters/styles.module.css

Fix misaligned icon on homepage

---

docs/developer/extending/webhooks/synchronous-events/shipping.mdx

This PR adds specifics on how to fetch shipping method IDs when using synchronous shipping events without creating a circular reference

Fix misleading info on shippingMethods fetching in subscription queries

---

docs/api-usage/metadata.mdx

Remove note to use checkout or order token as id in updateMetadata 
Highlight that updateMetadata require permission for updating object

Remove note about using order token in updateMetadata

---

docs/developer/extending/apps/extending-dashboard-with-apps.mdx
docs/developer/menu.mdx
docs/developer/modeling.mdx
docs/developer/models.mdx
docs/developer/payments/refunds.mdx
docs/developer/structures.mdx
docs/index.mdx
sidebars/core-concepts.js
vercel.json

Renames "pages" to "models" and "menus" to "structures" with API compatibility note.

Rename "pages" to "models" and "menus" to "structures"
